force-app/main/default/objects/Contract_Line_Items__c/Contract_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This object captures Contract Line Items.</description>
    <label>Contract Line Items</label>
    <nameField>
        <displayFormat>CLI-{0}</displayFormat>
        <label>Contract Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Line_Items__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>This field denotes the Contract Line Item end date.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Items__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>This field denotes the Quantity.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Items__c/fields/Revenue_Contract_Details__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract_Details__c</fullName>
    <description>This field denotes the revenue contract.</description>
    <label>Revenue Contract Details</label>
    <referenceTo>Revenue_Contract__c</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Items__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>This field denotes the Contract Line Item Start Date.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Items__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>This field denotes the overriden Product Unit Price</description>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <label>Payment Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/Quota__c.object-meta.xml
<CustomObject>
    <label>Quota</label>
    <nameField>
        <displayFormat>QTA-{MMDDYYYY}-{00}</displayFormat>
        <label>Quota Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quota</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Quota</relationshipLabel>
    <relationshipName>Quota</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Monthly_Quota_Amount__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Quota_Amount__c</fullName>
    <label>Monthly Quota Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Quota_End_Date__c</fullName>
    <label>Quota End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Quota_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quota Schedule</label>
    <referenceTo>Quota_Schedule__c</referenceTo>
    <relationshipLabel>Quota</relationshipLabel>
    <relationshipName>Quota</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Quota_Start_Date__c</fullName>
    <label>Quota Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/Quota_Schedule__c.object-meta.xml
<CustomObject>
    <label>Quota Schedule</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Quota Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quota Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota_Schedule__c/fields/Monthly_Amount__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Amount__c</fullName>
    <formula>ROUND((Quota_Amount__c/12)/Value(Text(Type__c)),2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/fields/Range_End__c.field-meta.xml
<CustomField>
    <fullName>Range_End__c</fullName>
    <label>Range End</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/fields/Range_Start__c.field-meta.xml
<CustomField>
    <fullName>Range_Start__c</fullName>
    <label>Range Start</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Annually</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/Revenue_Account__c.object-meta.xml
<CustomObject>
    <label>Revenue Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Account__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Revenue Accounts</relationshipLabel>
    <relationshipName>Revenue_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/fields/Billing_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Billing_Cycle__c</fullName>
    <label>Billing Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Semi Annually</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Annually</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Revenue</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Revenue Accounts</relationshipLabel>
    <relationshipName>Revenue_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Account</label>
    <referenceTo>Payment_Account__c</referenceTo>
    <relationshipLabel>Revenue Accounts</relationshipLabel>
    <relationshipName>Revenue_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/fields/Quota__c.field-meta.xml
<CustomField>
    <fullName>Quota__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quota</label>
    <referenceTo>Quota__c</referenceTo>
    <relationshipLabel>Revenue Accounts</relationshipLabel>
    <relationshipName>Revenue_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/Revenue_Contract__c.object-meta.xml
<CustomObject>
    <description>This object captures the revenue Contract.</description>
    <label>Revenue Contract / Statement of Work</label>
    <nameField>
        <displayFormat>RC/SOW - {0000}</displayFormat>
        <label>Revenue Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract__c/fields/Batch_Process_Execution__c.field-meta.xml
<CustomField>
    <fullName>Batch_Process_Execution__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Process Execution</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>This field denotes the Contract End Date</description>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <description>This field denotes the Start Date.</description>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <description>This field denotes the Invoice Date.</description>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Live_Renewed_Date__c.field-meta.xml
<CustomField>
    <fullName>Live_Renewed_Date__c</fullName>
    <description>This field denotes the Live/Renewed Date.</description>
    <label>Live/Renewed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Payment_Term_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_After_Days__c</fullName>
    <description>This field denotes the Payment Term (After # Days).</description>
    <label>Payment Term (After # Days)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term_After_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Account__c</fullName>
    <description>This field denotes the parent Revenue Account.</description>
    <label>Revenue Account</label>
    <referenceTo>Revenue_Account__c</referenceTo>
    <relationshipLabel>Revenue Contract / Statement of Work</relationshipLabel>
    <relationshipName>Revenue_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Term_After_Days.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <default>true</default>
        <label>On Delivery</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Net 15</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Net 30</label>
    </customValue>
    <customValue>
        <fullName>45</fullName>
        <label>Net 45</label>
    </customValue>
    <customValue>
        <fullName>60</fullName>
        <label>Net 60</label>
    </customValue>
    <customValue>
        <fullName>75</fullName>
        <label>Net 75</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>Net 90</label>
    </customValue>
    <masterLabel>Payment Term (After # Days)</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuotaTriggerHandler.cls
/*
Description : Handler class to Quota trigger.
Date Created : 5th June 2019
Change 1 :  PCPM-316 | 22 JULY 19 | Namita 
*/

public with sharing class QuotaTriggerHandler implements CommonTriggerHandler{
    public static List<Quota_Schedule__c> quoataSchdule;
    public static String RA_General_RTID;
    static{
        Schema.DescribeSObjectResult raSchema = Revenue_Account__c.sObjectType.getDescribe();
        Map<String,Schema.RecordTypeInfo>  recordTypeInfoRA = raSchema.getRecordTypeInfosByDeveloperName(); 
        RA_General_RTID = recordTypeInfoRA.get(CONSTANT.REVENUE_RECORD_TYPE_GENERAL).getRecordTypeId();
        quoataSchdule = [Select id , Type__c , Range_Start__c , Range_End__c , Monthly_Amount__c from Quota_Schedule__c where Range_Start__c != null order by Name];
    }
    
    
    public void BeforeInsert(List<SObject> newItems){
        
    }
    
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems){
        
    }
    
    public void BeforeDelete(Map<Id, SObject> oldItems){
        deleteRevenueAccount((Map<Id, Quota__c>)oldItems);
    }
    
    public void AfterInsert(Map<Id, SObject> newItems){
        insertRevenueAccount((Map<Id, Quota__c>)newItems, null);
    }
    
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems){
        insertRevenueAccount((Map<Id, Quota__c>)newItems, (Map<Id, Quota__c>)oldItems);
    }
    
    public void AfterDelete(Map<Id, SObject> oldItems){
        
    }
    
    public void AfterUndelete(Map<Id, SObject> oldItems){
        
    }
    
    public Boolean IsDisabled(){
        return false;
    }
    
    /* This method will create revenue account
     * @param 
       newItems : new map of quota id to quota record
       @return null
     */
    public void insertRevenueAccount(Map<Id, Quota__c> newItems, Map<Id, Quota__c> oldItems){
        Boolean isInsert = oldItems == null;
        Revenue_Account__c revenueAccount;
        Revenue_Contract__c revenueContract;
        Map<String, Double> quotaToAmount = new Map<String, Double>();
        List<Revenue_Contract__c> revenueContractsList = new List<Revenue_Contract__c>();
        List<Revenue_Account__c> deleteRevenueAccounts = new List<Revenue_Account__c>();
        Map<Revenue_Contract__c,Revenue_Account__c> mapRContractToRAccout = new Map<Revenue_Contract__c,Revenue_Account__c>();
        Map<String, Revenue_Contract__c> mapQuotaToContract = new Map<String, Revenue_Contract__c>();
        List<Quota_Schedule__c> quoataSchdule;
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.QUOTA_SCHEDULE_OBJECT,'id , Type__c , Range_Start__c , Range_End__c , Monthly_Amount__c',Constant.ACTION_TYPE_ACCESS)){
        	quoataSchdule =  [Select id , Type__c , Range_Start__c , Range_End__c , Monthly_Amount__c from Quota_Schedule__c limit 1];
    	}
        Integer months = 0;
        if(quoataSchdule.size() > 0){
            months = Integer.valueOf(quoataSchdule[0].Type__c);
        }
        
        if(!isInsert) {
            if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_CONTRACT_OBJECT,'Id,Revenue_Account__c, Live_Renewed_Date__c,Contract_Start_Date__c',Constant.ACTION_TYPE_ACCESS) &&
               PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'Quota__c',Constant.ACTION_TYPE_ACCESS)
              ){
                for(Revenue_Contract__c ra : [Select Id,Revenue_Account__c, Live_Renewed_Date__c,
                                              Revenue_Account__r.Quota__c,Contract_Start_Date__c,
                                              (Select Id From Contract_Line_Items__r)
                                              From Revenue_Contract__c where Revenue_Account__r.Quota__c in: oldItems.keySet()]) {
                                                  mapQuotaToContract.put(ra.Revenue_Account__r.Quota__c +':'+ra.Contract_Start_Date__c, ra);
                                              }
        	} 

        }
        PlaceCPM_Utility.getAssumption();
        Boolean isContractStartDate = false, isLiveRenewDate = false, isInvoiceDate = false, isName = false;
        Boolean isRecordType = false, isGLCode = false, isAccountExecutive = false, isPaymentAccount = false;
        Boolean isQuota = false, isContractEndDate = false, isPaymentTermAfterDays = false, isRevenueAccountBillingCycle = false;
        
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_CONTRACT_OBJECT,'Contract_Start_Date__c',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_CONTRACT_OBJECT,'Contract_Start_Date__c',Constant.ACTION_TYPE_INSERT)){
        	isContractStartDate = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_CONTRACT_OBJECT,'Live_Renewed_Date__c',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_CONTRACT_OBJECT,'Live_Renewed_Date__c',Constant.ACTION_TYPE_INSERT)){
            isLiveRenewDate = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_CONTRACT_OBJECT,'Invoice_Date__c',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_CONTRACT_OBJECT,'Invoice_Date__c',Constant.ACTION_TYPE_INSERT)){
            isInvoiceDate = true;
        }
        //PCPM-316
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'Name',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'Name',Constant.ACTION_TYPE_INSERT)){
            isName = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'RecordTypeId',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'RecordTypeId',Constant.ACTION_TYPE_INSERT)){
            isRecordType = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'GL_Code__c',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'GL_Code__c',Constant.ACTION_TYPE_INSERT)){
            isGLCode = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'Account_Executive__c',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'Account_Executive__c',Constant.ACTION_TYPE_INSERT)){
            isAccountExecutive = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'Payment_Account__c',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'Payment_Account__c',Constant.ACTION_TYPE_INSERT)){
            isPaymentAccount = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'Quota__c',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'Quota__c',Constant.ACTION_TYPE_INSERT)){
            isQuota = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_CONTRACT_OBJECT,'Contract_End_Date__c',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_CONTRACT_OBJECT,'Contract_End_Date__c',Constant.ACTION_TYPE_INSERT)){
            isContractEndDate = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_CONTRACT_OBJECT,'Payment_Term_After_Days__c',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_CONTRACT_OBJECT,'Payment_Term_After_Days__c',Constant.ACTION_TYPE_INSERT)){
            isPaymentTermAfterDays = true;
        }
        
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'Billing_Cycle__c',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'Billing_Cycle__c',Constant.ACTION_TYPE_INSERT)){
        	isRevenueAccountBillingCycle = true;                   
		}
        for(Quota__c q : newItems.values()){
            if(q.Employee__c != null 
               && PlaceCPM_Utility.assumptionRevenueGLAccount != null
               && q.Monthly_Quota_Amount__c != null 
               && q.Quota_Start_Date__c != null 
               && q.Quota_End_Date__c != null ){
                   quotaToAmount.put(q.Id, q.Monthly_Quota_Amount__c);
                   For(Integer i=0 ; i < months ; i++){
                       revenueAccount = new Revenue_Account__c();
                       revenueContract = new Revenue_Contract__c();
                       if(isContractStartDate){
                            revenueContract.Contract_Start_Date__c = q.Quota_Start_Date__c.addMonths(i);
                       }
                       String key = q.Id +':'+revenueContract.Contract_Start_Date__c;
                       if(mapQuotaToContract.containsKey(key)) {
                           system.debug(key);
                           revenueContract = mapQuotaToContract.get(key);
                           revenueAccount.Id = revenueContract.Revenue_Account__c;
                           //revenueContract.Id = mapQuotaToContract.get(key).Id;
                       }
                       if(isLiveRenewDate){
                            revenueContract.Live_Renewed_Date__c = revenueContract.Contract_Start_Date__c;
                       }
                       if(isInvoiceDate){
                            revenueContract.Invoice_Date__c = revenueContract.Contract_Start_Date__c;
                       }
                       if(isName){
                            revenueAccount.Name = System.Label.Quota+' - '+ placeCPM_Utility.getMonthString(revenueContract.Live_Renewed_Date__c.month()) + ' ' +revenueContract.Live_Renewed_Date__c.year();
                       }
                       if(isRecordType){
                            revenueAccount.RecordTypeId = RA_General_RTID;
                       }
                       if(isGLCode){
                            revenueAccount.GL_Code__c = PlaceCPM_Utility.assumptionRevenueGLAccount;
                       }
                       if(isAccountExecutive){
                            revenueAccount.Account_Executive__c = q.Employee__c;
                       }
                       if(isPaymentAccount){
                            revenueAccount.Payment_Account__c = PlaceCPM_Utility.assumptionPaymentAccount;
                       }
                       if(isQuota){
                            revenueAccount.Quota__c = q.Id;
                       }
                       if(isContractEndDate){
                            revenueContract.Contract_End_Date__c = q.Quota_Start_Date__c.addMonths(i+PlaceCPM_Utility.contractDuration-1);
                       }
                       if(isPaymentTermAfterDays){
                            revenueContract.Payment_Term_After_Days__c = '0';
                       }
                       
                       if(PlaceCPM_Utility.empRevDetailWrapper.containsKey(q.Employee__c) && revenueContract.Contract_End_Date__c > PlaceCPM_Utility.empRevDetailWrapper.get(q.Employee__c).maxContractEndDate 
                       && revenueContract.Contract_Start_Date__c < PlaceCPM_Utility.empRevDetailWrapper.get(q.Employee__c).maxContractEndDate 
                       && isContractEndDate) {
                           revenueContract.Contract_End_Date__c = PlaceCPM_Utility.empRevDetailWrapper.get(q.Employee__c).maxContractEndDate;
                       }
                       if(isRevenueAccountBillingCycle){
                            revenueAccount.Billing_Cycle__c = PlaceCPM_Utility.billingCycle;
                       }
                       if(revenueContract.Contract_Start_Date__c >= q.Quota_End_Date__c) {
                           if(revenueAccount.Id != null) {
                               deleteRevenueAccounts.add(revenueAccount);
                           }
                       } else {
                           revenueContractsList.add(revenueContract);
                           mapRContractToRAccout.put(revenueContract,revenueAccount);
                       }
                   }
               }
        }
        PlaceCPM_Utility.deleteRecords(deleteRevenueAccounts, CONSTANT.revenueAccountObject, false); //520
        if(mapRContractToRAccout.size() > 0) {
          PlaceCPM_Utility.upsertRecords(mapRContractToRAccout.values(), CONSTANT.revenueAccountObject, false); //520
          insertRevenueContract(mapRContractToRAccout, quotaToAmount);
        }
    }
    
    /* This method will create revenue contract
     * @param 
       listOfRevenueAccounts : List of Revenue_Account__c records
       quotaToAmount : Map of Quata Id to Quota Amount
       @return null
      */
    public void insertRevenueContract(Map<Revenue_Contract__c,Revenue_Account__c> mapRContractToRAccout, Map<String, Double> quotaToAmount){
        Revenue_Account__c revenueAccount;
        List<Revenue_Contract__c> listOfRevenueContract = new List<Revenue_Contract__c>();
        Map<String,  Revenue_Contract__c> revenueAccountToRevenueContractMap = new Map<String,  Revenue_Contract__c>();
        Boolean isRevenueAccount = false, isBatchProcessExecution = false;
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_CONTRACT_OBJECT,'Revenue_Account__c',Constant.ACTION_TYPE_INSERT)){
        	isRevenueAccount = true;
        }
        if (PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_CONTRACT_OBJECT,'Batch_Process_Execution__c',Constant.ACTION_TYPE_UPDATE)){
        	isBatchProcessExecution = true;
        }
        for(Revenue_Contract__c revenueContract : mapRContractToRAccout.keySet()) {
            revenueAccount = mapRContractToRAccout.get(revenueContract);
            if(revenueContract.Revenue_Account__c == null){
                if(isRevenueAccount){
                    revenueContract.Revenue_Account__c = revenueAccount.Id;
                }
            }
            if (isBatchProcessExecution){
                revenueContract.Batch_Process_Execution__c = true;
            }
            quotaToAmount.put(revenueAccount.Id, quotaToAmount.get(revenueAccount.Quota__c));
            listOfRevenueContract.add(revenueContract);
            revenueAccountToRevenueContractMap.put(revenueAccount.Id, revenueContract);
        }

        PlaceCPM_Utility.upsertRecords(listOfRevenueContract, CONSTANT.REVENUE_CONTRACT_OBJECT, false); //520
        insertContractLineItem(listOfRevenueContract, quotaToAmount, revenueAccountToRevenueContractMap);
    }
    
    /* This method will create contract line item
     * @param 
       listOfRevenueContract : List of Revenue_Contract__c records
       quotaToAmount : Map of Quata Id to Quota Amount
       @return null
      */
    public void insertContractLineItem(List<Revenue_Contract__c> listOfRevenueContract, Map<String, Double> quotaToAmount, Map<String,  Revenue_Contract__c> revenueAccountToRevenueContractMap){
        Contract_Line_Items__c cli ;
        List<Contract_Line_Items__c> listOfContractLineItem = new List<Contract_Line_Items__c>();
        Boolean isUnitPrice = false, isRevenueContractDetails = false, isStartDate = false, isEndDate = false, isRevenueContractId = false, isQuantity = false;
        if (PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CONTRACT_LINE_ITEM_OBJECT,'Unit_Price__c',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CONTRACT_LINE_ITEM_OBJECT,'Unit_Price__c',Constant.ACTION_TYPE_INSERT)){
            isUnitPrice = true;
        }
        if (PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CONTRACT_LINE_ITEM_OBJECT,'Revenue_Contract_Details__c',Constant.ACTION_TYPE_INSERT)){
            isRevenueContractDetails = true;
        }
        if (PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CONTRACT_LINE_ITEM_OBJECT,'Start_Date__c',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CONTRACT_LINE_ITEM_OBJECT,'Start_Date__c',Constant.ACTION_TYPE_INSERT)){
            isStartDate = true;
        }
        if (PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CONTRACT_LINE_ITEM_OBJECT,'End_Date__c',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CONTRACT_LINE_ITEM_OBJECT,'End_Date__c',Constant.ACTION_TYPE_INSERT)){
            isEndDate = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CONTRACT_LINE_ITEM_OBJECT,'Id',Constant.ACTION_TYPE_INSERT)){
            isRevenueContractId = true;
        }
        if (PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CONTRACT_LINE_ITEM_OBJECT,'Quantity__c',Constant.ACTION_TYPE_UPDATE) && PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CONTRACT_LINE_ITEM_OBJECT,'Quantity__c',Constant.ACTION_TYPE_INSERT)){
            isQuantity = true;
        }
        
        for(Revenue_Contract__c revenueContract : listOfRevenueContract) {
            cli = new Contract_Line_Items__c ();
            if (isUnitPrice){
                cli.Unit_Price__c = PlaceCPM_Utility.assumptionAvgLicenserPrice;
            }
            if (isRevenueContractDetails){
                cli.Revenue_Contract_Details__c = revenueContract.Id;
            }
            if (isStartDate){
                cli.Start_Date__c = revenueContract.Contract_Start_Date__c;
            }
            if (isEndDate){
                cli.End_Date__c = revenueContract.Contract_End_Date__c;
            }
            if(revenueAccountToRevenueContractMap.containsKey(revenueContract.Revenue_Account__c)
              && revenueAccountToRevenueContractMap.get(revenueContract.Revenue_Account__c).Contract_Line_Items__r != null
              && revenueAccountToRevenueContractMap.get(revenueContract.Revenue_Account__c).Contract_Line_Items__r.size() > 0
              ) {
                if(isRevenueContractId){
                    cli.Id = revenueAccountToRevenueContractMap.get(revenueContract.Revenue_Account__c).Contract_Line_Items__r[0].Id;
                }
            }
            if(cli.Unit_Price__c != null && cli.Unit_Price__c != 0) {
                if (isQuantity){
                    cli.Quantity__c = (quotaToAmount.get(revenueContract.Revenue_Account__c)*(PlaceCPM_Utility.assumptionForecastQuota/100))/cli.Unit_Price__c;
                }
                listOfContractLineItem.add(cli);
            }
        }
        PlaceCPM_Utility.upsertRecords(listOfContractLineItem, CONSTANT.CONTRACT_LINE_ITEM_OBJECT, false); //520
    }
    
    public void deleteRevenueAccount(Map<Id, Quota__c> oldItems){
        PlaceCPM_Utility.deleteRecords([Select Id From Revenue_Account__c WHERE Quota__c in: oldItems.keySet()], CONSTANT.revenueAccountObject, false); //520
    }
}