force-app/main/default/objects/Contract_Line_Items__c/Contract_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This object captures Contract Line Items.</description>
    <label>Contract Line Items</label>
    <nameField>
        <displayFormat>CLI-{0}</displayFormat>
        <label>Contract Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Line_Items__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>This field denotes the Contract Line Item end date.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Items__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field denotes the revenue product.</description>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Items__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>This field denotes the Quantity.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Items__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>This field denotes the Contract Line Item Start Date.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Items__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <description>This field denotes the Total Amount.</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <label>Payment Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <description>This object records Revenue Product.</description>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Account__c/Revenue_Account__c.object-meta.xml
<CustomObject>
    <label>Revenue Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Account__c/fields/Billing_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Billing_Cycle__c</fullName>
    <label>Billing Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Semi Annually</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Annually</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Revenue</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Revenue Accounts</relationshipLabel>
    <relationshipName>Revenue_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Account</label>
    <referenceTo>Payment_Account__c</referenceTo>
    <relationshipLabel>Revenue Accounts</relationshipLabel>
    <relationshipName>Revenue_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Cash_Allocation__c/Revenue_Cash_Allocation__c.object-meta.xml
<CustomObject>
    <label>Revenue Cash Allocation</label>
    <nameField>
        <displayFormat>RCA-{000000}-{000}</displayFormat>
        <label>Revenue Cash Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Cash Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Cash_Allocation__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Revenue Cash Allocations</relationshipLabel>
    <relationshipName>Revenue_Cash_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Cash_Allocation__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <formula>IF(NOT( ISBLANK(Revenue_Account__c)),IF(NOT( ISBLANK(Revenue_Account__r.Payment_Account__c)), CASESAFEID(Revenue_Account__r.Payment_Account__r.Name), CASESAFEID(Revenue_Account__r.Account_Executive__r.Location__r.Payment_Account__r.Name)), IF(NOT(ISBLANK(Equity__c)),CASESAFEID(Equity__r.Payment_Account__r.Name), null ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_Cash_Allocation__c/fields/Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Account</label>
    <referenceTo>Revenue_Account__c</referenceTo>
    <relationshipLabel>Revenue Cash Allocations</relationshipLabel>
    <relationshipName>Revenue_Cash_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Cash_Allocation__c/fields/Revenue_Contract__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field denotes the parent Revenue contract</description>
    <label>Revenue Contract</label>
    <referenceTo>Revenue_Contract__c</referenceTo>
    <relationshipLabel>Revenue Cash Allocations</relationshipLabel>
    <relationshipName>Revenue_Cash_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/Revenue_Contract__c.object-meta.xml
<CustomObject>
    <description>This object captures the revenue Contract.</description>
    <label>Revenue Contract / Statement of Work</label>
    <nameField>
        <displayFormat>RC/SOW - {0000}</displayFormat>
        <label>Revenue Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract__c/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Auto Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>This field denotes the Contract End Date</description>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <description>This field denotes the Start Date.</description>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <description>This field denotes the Invoice Date.</description>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Live_Renewed_Date__c.field-meta.xml
<CustomField>
    <fullName>Live_Renewed_Date__c</fullName>
    <description>This field denotes the Live/Renewed Date.</description>
    <label>Live/Renewed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Payment_Term_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_After_Days__c</fullName>
    <description>This field denotes the Payment Term (After # Days).</description>
    <label>Payment Term (After # Days)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term_After_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Account__c</fullName>
    <description>This field denotes the parent Revenue Account.</description>
    <label>Revenue Account</label>
    <referenceTo>Revenue_Account__c</referenceTo>
    <relationshipLabel>Revenue Contract / Statement of Work</relationshipLabel>
    <relationshipName>Revenue_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Revenue_P_L_Allocation__c/Revenue_P_L_Allocation__c.object-meta.xml
<CustomObject>
    <label>Revenue GL Allocation</label>
    <nameField>
        <displayFormat>RPLA-{000000}-{000}</displayFormat>
        <label>Revenue P&amp;L Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue GL Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_P_L_Allocation__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Revenue GL Allocations</relationshipLabel>
    <relationshipName>Revenue_P_L_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_P_L_Allocation__c/fields/Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Account</label>
    <referenceTo>Revenue_Account__c</referenceTo>
    <relationshipLabel>Revenue GL Allocations</relationshipLabel>
    <relationshipName>Revenue_P_L_Allocations_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_P_L_Allocation__c/fields/Revenue_Contract__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field denotes the parent Revenue Contract.</description>
    <label>Revenue Contract</label>
    <referenceTo>Revenue_Contract__c</referenceTo>
    <relationshipLabel>Revenue GL Allocations</relationshipLabel>
    <relationshipName>Revenue_P_L_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SOW_Line_Item__c/SOW_Line_Item__c.object-meta.xml
<CustomObject>
    <label>SOW Line Item</label>
    <nameField>
        <displayFormat>SOWLI- {0000}</displayFormat>
        <label>SOW Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SOW Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Payment_Term_After_Days.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <default>true</default>
        <label>On Delivery</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Net 15</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Net 30</label>
    </customValue>
    <customValue>
        <fullName>45</fullName>
        <label>Net 45</label>
    </customValue>
    <customValue>
        <fullName>60</fullName>
        <label>Net 60</label>
    </customValue>
    <customValue>
        <fullName>75</fullName>
        <label>Net 75</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>Net 90</label>
    </customValue>
    <masterLabel>Payment Term (After # Days)</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RevenueContractTriggerTest.cls
@isTest
public class RevenueContractTriggerTest {
    public static List<Revenue_Account__c> revenueAccountList;
    public static List<Payment_Account__c> paymentAccountList;
    public static List<Account> accountList;
    public static List<Revenue_Contract__c> revenueContractList;
    public static List<GL_Code__c> glCodeList;
    public static List<Contract_Line_Items__c> listContractLineItems;
    public static List<Product__c> listProduct;
    private static void initData(){
        TestUtility.createAssumption(24,true);
        accountList= new List<Account>();
        paymentAccountList = new List<Payment_Account__c>();
        revenueAccountList = new List<Revenue_Account__c>();
        revenueContractList = new List<Revenue_Contract__c>();
        listProduct = new List<Product__c>();
        glCodeList = new List<GL_Code__c>();
        listContractLineItems = new List<Contract_Line_Items__c>();
        accountList.add(TestUtility.createAccount('testAccount',true));
        paymentAccountList.add(TestUtility.createPaymentAccount('testPaymentAccount',true));
        glCodeList.add(TestUtility.createGLCode('test GL code',1111,TestUtility.createPlCategory('test PL category','Revenue',true).Id,true));
        revenueAccountList.add(TestUtility.createRevenueAccount(accountList[0].Id,glCodeList[0].Id,paymentAccountList[0].Id,'1',true));
        listProduct.add(TestUtility.createProduct('test product','Product',10,'License',true));
        
    }
    //#124
    @isTest
    public static void insertRevenueContract(){
        initData();
        Revenue_Contract__c rc = new Revenue_Contract__c();
        //PCPM-315 
        rc.recordTypeId = Schema.SObjectType.Revenue_Contract__c.getRecordTypeInfosByName().get(CONSTANT.RECURRING_RECORD_TYPE_RC).getRecordTypeId();
        rc.Contract_Start_Date__c = Date.newInstance(2020, 1, 1); 
        rc.Revenue_Account__c = revenueAccountList[0].Id;       
        rc.Live_Renewed_Date__c = Date.newInstance(2020, 1, 4);//PCPM-315 
        rc.Contract_Start_Date__c = Date.newInstance(2020, 1, 4);//PCPM-315 
        rc.Contract_End_Date__c = Date.newInstance(2020, 9, 30);//PCPM-315  
        rc.Invoice_Date__c = Date.newInstance(2020, 1, 10);//PCPM-315 
        rc.Payment_Term_After_Days__c = '15';
        rc.Auto_Renew__c = true;
        
        Test.startTest();
        insert rc;
        // Inserting CLI will update the Total Monthly Revenue and trigger the upsertion of PnL Allocation records
        listContractLineItems.add(TestUtility.createContractLineItem('test CLI',rc.Id,10,listProduct[0].Id,true));
		List<Revenue_P_L_Allocation__c> listRevenuePLAllocation = [SELECT ID FROM Revenue_P_L_Allocation__c 
                                                                   WHERE Revenue_Contract__c = :rc.Id];
        List<Revenue_Cash_Allocation__c > listRevenueCashAllocation = [SELECT ID FROM Revenue_Cash_Allocation__c  
                                                                   WHERE Revenue_Contract__c = :rc.Id];
        
        // Extending the Revenue Contract end date to test increase in PNL records
        rc.Contract_End_Date__c = Date.newInstance(2020, 12, 31);
        update rc; 
        listContractLineItems[0].Quantity__c = 20;
        update listContractLineItems;
        //#133
        listContractLineItems[0].Start_Date__c  = Date.newInstance(2020, 2, 1);
        listContractLineItems[0].End_Date__c  = Date.newInstance(2020, 4, 31);
        update listContractLineItems;
        Test.stopTest();
        
        List<Revenue_P_L_Allocation__c> listRevenuePLAllocationUpdated = [SELECT ID FROM Revenue_P_L_Allocation__c 
                                                                   WHERE Revenue_Contract__c = :rc.Id];
        System.assert(listRevenuePLAllocation.size() > 0);
        System.assert(listRevenueCashAllocation.size() > 0);
        System.AssertEquals(listRevenuePLAllocation.size(), 22); //PCPM-315 | 411
        System.debug('SOW record type'+rc.RecordTypeId);
        
		//Deleting the Revenue Contract
		delete rc;
        //Not required.Written to cover RevenueAccountTrigger
        revenueAccountList[0].Billing_Cycle__c = '6';
        update revenueAccountList;
        delete revenueAccountList;
        
    }
    //#33
    @isTest
    public static void insertSOW(){
        initData();
        revenueAccountList[0].recordTypeId = Schema.SObjectType.Revenue_Account__c.getRecordTypeInfosByName().get(CONSTANT.REVENUE_RECORD_TYPE_TnM).getRecordTypeId();
		update revenueAccountList;
        Revenue_Contract__c rc = new Revenue_Contract__c();
        rc.recordTypeId = Schema.SObjectType.Revenue_Contract__c.getRecordTypeInfosByName().get(CONSTANT.REVENUE_CONTRACT_RECORD_TYPE_SOW).getRecordTypeId();
        rc.Revenue_Account__c = revenueAccountList[0].Id;
        rc.Live_Renewed_Date__c = Date.newInstance(2020, 1, 1);
        rc.Contract_Start_Date__c = Date.newInstance(2020, 1, 1);
        rc.Contract_End_Date__c = Date.newInstance(2020, 9, 30); 
        rc.Invoice_Date__c = Date.newInstance(2020, 1, 1);
        rc.Payment_Term_After_Days__c = '15';
        rc.Total_Amount__c=1000.0;
        
        Test.startTest();
        insert rc;
        Test.stopTest();
        SOW_Line_Item__c sowli=TestUtility.createSOWLineItem(rc.Id,'March','2020',100,true);
        TestUtility.createSOWLineItem(rc.Id,'April','2020',100,true);
        
        List<Revenue_P_L_Allocation__c> listRevenuePLAllocation = [SELECT ID FROM Revenue_P_L_Allocation__c 
                                                                   WHERE Revenue_Contract__c = :rc.Id];
        System.assertEquals(2, listRevenuePLAllocation.size());
    }

}