force-app/main/default/objects/Contract_Line_Items__c/Contract_Line_Items__c.object-meta.xml
<CustomObject>
    <description>This object captures Contract Line Items.</description>
    <label>Contract Line Items</label>
    <nameField>
        <displayFormat>CLI-{0}</displayFormat>
        <label>Contract Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Role</label>
    <referenceTo>Role__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <label>Payment Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/Quota__c.object-meta.xml
<CustomObject>
    <label>Quota</label>
    <nameField>
        <displayFormat>QTA-{MMDDYYYY}-{00}</displayFormat>
        <label>Quota Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quota</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Quota</relationshipLabel>
    <relationshipName>Quota</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/Revenue_Account__c.object-meta.xml
<CustomObject>
    <label>Revenue Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Account__c/fields/Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Executive</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Revenue Accounts</relationshipLabel>
    <relationshipName>Revenue_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Revenue</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Revenue Accounts</relationshipLabel>
    <relationshipName>Revenue_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Account</label>
    <referenceTo>Payment_Account__c</referenceTo>
    <relationshipLabel>Revenue Accounts</relationshipLabel>
    <relationshipName>Revenue_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/fields/Quota__c.field-meta.xml
<CustomField>
    <fullName>Quota__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quota</label>
    <referenceTo>Quota__c</referenceTo>
    <relationshipLabel>Revenue Accounts</relationshipLabel>
    <relationshipName>Revenue_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/Revenue_Contract__c.object-meta.xml
<CustomObject>
    <description>This object captures the revenue Contract.</description>
    <label>Revenue Contract / Statement of Work</label>
    <nameField>
        <displayFormat>RC/SOW - {0000}</displayFormat>
        <label>Revenue Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract__c/fields/Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Account__c</fullName>
    <description>This field denotes the parent Revenue Account.</description>
    <label>Revenue Account</label>
    <referenceTo>Revenue_Account__c</referenceTo>
    <relationshipLabel>Revenue Contract / Statement of Work</relationshipLabel>
    <relationshipName>Revenue_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RevenueAccountTriggerTest.cls
/*
Class Name   : RevenueAccountTriggerTest
Description  : This class will cover funactionality related to Revenue Account object.

Change 1 :  1 SEPT 19 
*/
@isTest
public class RevenueAccountTriggerTest {
     public static List<Revenue_Account__c> revenueAccountList;
    public static List<Payment_Account__c> paymentAccountList;
    public static List<Account> accountList;
    public static List<Revenue_Contract__c> revenueContractList;
    public static List<GL_Code__c> glCodeList;
    public static List<Contract_Line_Items__c> listContractLineItems;
    public static Employee__c employee;
    public static Department__c department;
    public static Role__c role;
    public static Quota__c quota;
    
    private static void createData(){
        TestUtility.createAssumption(24,true);
        accountList= new List<Account>();
        paymentAccountList = new List<Payment_Account__c>();
        revenueAccountList = new List<Revenue_Account__c>();
        glCodeList = new List<GL_Code__c>();
        listContractLineItems = new List<Contract_Line_Items__c>();
        accountList.add(TestUtility.createAccount('testAccount',true));
        paymentAccountList.add(TestUtility.createPaymentAccount('testPaymentAccount',true));
        glCodeList.add(TestUtility.createGLCode('test GL code',1111,TestUtility.createPlCategory('test PL category','Revenue',true).Id,true));
        revenueAccountList.add(TestUtility.createRevenueAccount(accountList[0].Id,glCodeList[0].Id,paymentAccountList[0].Id,'1',false));
        String recordTypeIdEmployee = Schema.SObjectType.Employee__c.getRecordTypeInfosByName().get('Sales Employee').getRecordTypeId();
        
        department = TestUtility.createDepartment('test department', TestUtility.createOrganisation('Org test',true).Id,glCodeList[0].Id,true);
        role = TestUtility.createRole('Role Name',department.id,true);
        employee = TestUtility.createEmployee('Test employee',role.Id,System.today(),'Austin','Salaried Employee',recordTypeIdEmployee,true);
        quota = TestUtility.createQuota(employee.Id,100.0,System.today(),system.today().addMonths(1),glCodeList[0].Id,true);
        
        
    }
    
    @isTest
    public static void testInvesmtent(){
        createData();
        System.debug('employee.Id'+employee.Id);
        revenueAccountList[0].Account_Executive__c =employee.Id;
        insert revenueAccountList;
        
        //Update case
        revenueAccountList[0].Name = 'test updated';
        revenueAccountList[0].Quota__c = quota.Id;
        //revenueAccountList[0].Account_Executive__c =employee.Id;
        update revenueAccountList;
        //Making quota null
        revenueAccountList[0].Quota__c = null;
        update revenueAccountList;
        
        //Delete Case
        delete revenueAccountList;
        
        //assert
        System.assertEquals(1, [Select Id from Employee__c where Name = 'Test employee'].size());
    }
}