force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>Comp - {00000}</displayFormat>
        <label>Compensation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compensation__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Compensations</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Wages__c/Wages__c.object-meta.xml
<CustomObject>
    <label>Wage</label>
    <nameField>
        <displayFormat>Wage-{00000000}</displayFormat>
        <label>Wages Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wages__c/fields/Compensation__c.field-meta.xml
<CustomField>
    <fullName>Compensation__c</fullName>
    <label>Compensation</label>
    <referenceTo>Compensation__c</referenceTo>
    <relationshipLabel>Wages</relationshipLabel>
    <relationshipName>Wages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wages__c/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Wages</relationshipLabel>
    <relationshipName>Wages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Wages__c/fields/Employer_Tax__c.field-meta.xml
<CustomField>
    <fullName>Employer_Tax__c</fullName>
    <label>Employer Tax %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Wages__c/fields/Employer_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Employer_Tax_Amount__c</fullName>
    <formula>IF( Compensation__r.Employee__r.RecordType.DeveloperName == &#39;Sales_Employee&#39;, (Employer_Tax__c) * ( Wage_Amount__c + Bonus_Amount__c ), IF(TEXT(Compensation__r.Employee__r.Employee_Type__c) == &#39;Salaried Employee&#39;, (Employer_Tax__c) * ( Wage_Amount__c + Bonus_Amount__c ),0) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employer Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Wages__c/fields/P_L_Date__c.field-meta.xml
<CustomField>
    <fullName>P_L_Date__c</fullName>
    <label>P&amp;L Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LocationTriggerHandler.cls
/*
 * Handler Class for LocationTrigger
 * createdOn 8August 2019
 */
public with sharing class LocationTriggerHandler implements CommonTriggerHandler{
	public static boolean dontRunTrigger = false;
    public void BeforeInsert(List<SObject> newItems){
        
    }
    
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems){
        
    }
    
    public void BeforeDelete(Map<Id, SObject> oldItems){

    }
    
    public void AfterInsert(Map<Id, SObject> newItems){
        
    }
    
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems){
        updateTaxPLs((List<Location__c>)newItems.values(),(Map<Id,Location__c>)oldItems);
    }
    
    public void AfterDelete(Map<Id, SObject> oldItems){
        
    }
    
    public void AfterUndelete(Map<Id, SObject> oldItems){
        
    }
    
    public Boolean IsDisabled(){
        return false;
    }
    
    public static void updateTaxPLs(List<Location__c> newItems, Map<Id,Location__c> oldItems){
        Set<String> locationIdSet = new Set<String>();
        Map<String,Decimal> locationIdSetForTaxChange = new Map<String,Decimal>();
        for(Location__c loc: newItems){
            if(loc.tax__c != null && (loc.Tax__c != oldItems.get(loc.Id).Tax__C || loc.GL_Code__c != oldItems.get(loc.Id).GL_Code__c	)){
                locationIdSet.add(loc.Id);
                if(loc.Tax__c != oldItems.get(loc.Id).Tax__C){
                    locationIdSetForTaxChange.put(loc.id,loc.Tax__c);
                }
            }
        }
        
        if(locationIdSetForTaxChange.size()>0){
            List<Wages__c> wagesToUpdate = new List<Wages__c>();
            Boolean isEmployeeTax = false;
            if(Schema.sObjectType.Wages__c.fields.Employer_Tax__c.isUpdateable()){
                isEmployeeTax = true;
            }
            
            if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.WAGES_OBJECT,'Id,P_L_Date__c,Cash_Date__c,Employee_Number__c, Employer_Tax_Amount__c,Compensation__c',Constant.ACTION_TYPE_ACCESS) &&
			   PlaceCPM_Utility.checkAccessiblityOfFields(Constant.COMPENSATION_OBJECT,'Employee__c',Constant.ACTION_TYPE_ACCESS) && 
               PlaceCPM_Utility.checkAccessiblityOfFields(Constant.EMPLOYEE_OBJECT,'location__c',Constant.ACTION_TYPE_ACCESS)){
                for(Wages__c wage : [SELECT Id,P_L_Date__c,Cash_Date__c,Employee_Number__c, Employer_Tax_Amount__c,Compensation__r.Employee__r.location__c   FROM wages__c WHERE Employee_Number__c IN (SELECT Id FROM employee__c WHERE location__c IN :locationIdSetForTaxChange.keySet()) AND Cash_Date__c >= TODAY]){
                    if(isEmployeeTax){
                        wage.Employer_Tax__c = locationIdSetForTaxChange.get(wage.Compensation__r.Employee__r.location__c);
                    }
                    wagesToUpdate.add(wage);
                }
        	}
            try{
                PlaceCPM_Utility.updateRecords(wagesToUpdate, CONSTANT.WAGES_OBJECT, false); //520
            }
            catch(Exception ex){
                PlaceCPM_Utility.debugLog(ex.getMessage() + ' at line number ' + ex.getLineNumber());
            }
            
        }
        if(locationIdSet.size()>0){
            
            List<Wages__c> wageList;
            if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.WAGES_OBJECT,'Id,P_L_Date__c,Cash_Date__c,Employee_Number__c, Employer_Tax_Amount__c',Constant.ACTION_TYPE_ACCESS)){
            	wageList = [SELECT Id,P_L_Date__c,Cash_Date__c,Employee_Number__c, Employer_Tax_Amount__c   FROM wages__c WHERE Employee_Number__c IN (SELECT Id FROM employee__c WHERE location__c IN :locationIdSet) AND Cash_Date__c >= TODAY];
        	}
            Set<Id> wageIdSet = new Set<Id>();
            for(Wages__c wage : wageList){
                wageIdSet.add(wage.Id);
            }
            WageTriggerHandler.deletePLAndCash(wageIdSet, true);
            WageTriggerHandler.createPL(wageList,true);
        }
    }
}