force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>Comp - {00000}</displayFormat>
        <label>Compensation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compensation__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Compensations</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor(Expense Account)</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Role</label>
    <referenceTo>Role__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Department_Allocation__c/Employee_Department_Allocation__c.object-meta.xml
<CustomObject>
    <label>Employee Department Allocation</label>
    <nameField>
        <displayFormat>EMPDA - {0000}</displayFormat>
        <label>Employee Department Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Department Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Department_Allocation__c/fields/Allocation_percentage__c.field-meta.xml
<CustomField>
    <fullName>Allocation_percentage__c</fullName>
    <label>Allocation percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Employee_Department_Allocation__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Department Allocations</relationshipLabel>
    <relationshipName>Employee_Department_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Department_Allocation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role</label>
    <referenceTo>Role__c</referenceTo>
    <relationshipLabel>Employee Department Allocations</relationshipLabel>
    <relationshipName>Employee_Department_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/Expense_Account__c.object-meta.xml
<CustomObject>
    <label>Expense Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Cash_Allocation__c/Expense_Cash_Allocation__c.object-meta.xml
<CustomObject>
    <label>Expense Cash Allocation</label>
    <nameField>
        <displayFormat>ECA-{000000}-{000}</displayFormat>
        <label>Expense Cash Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Cash Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/Cash_Date__c.field-meta.xml
<CustomField>
    <fullName>Cash_Date__c</fullName>
    <label>Cash Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense Cash Allocations</relationshipLabel>
    <relationshipName>Expense_Cash_Alllocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/Wage__c.field-meta.xml
<CustomField>
    <fullName>Wage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wage</label>
    <referenceTo>Wages__c</referenceTo>
    <relationshipLabel>Expense Cash Allocations</relationshipLabel>
    <relationshipName>Expense_Cash_Alllocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/Expense_PL_Allocation__c.object-meta.xml
<CustomObject>
    <label>Expense GL Allocation</label>
    <nameField>
        <displayFormat>EPLA-{000000}-{000}</displayFormat>
        <label>Expense P&amp;L Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense GL Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Wage_Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Wage__c.field-meta.xml
<CustomField>
    <fullName>Wage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Wage</label>
    <referenceTo>Wages__c</referenceTo>
    <relationshipName>Wage_Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wages__c/Wages__c.object-meta.xml
<CustomObject>
    <label>Wage</label>
    <nameField>
        <displayFormat>Wage-{00000000}</displayFormat>
        <label>Wages Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wages__c/fields/Bonus_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>Bonus_GL_Account__c</fullName>
    <formula>Compensation__r.Bonus_Plan__r.GL_Account__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bonus GL Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wages__c/fields/Bonus_Per_Wage__c.field-meta.xml
<CustomField>
    <fullName>Bonus_Per_Wage__c</fullName>
    <label>Bonus Per Wage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Wages__c/fields/Compensation__c.field-meta.xml
<CustomField>
    <fullName>Compensation__c</fullName>
    <label>Compensation</label>
    <referenceTo>Compensation__c</referenceTo>
    <relationshipLabel>Wages</relationshipLabel>
    <relationshipName>Wages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wages__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <formula>Employee_Number__r.First_Name__c  &amp; &quot; &quot; &amp;  Employee_Number__r.Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wages__c/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Name</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Wages</relationshipLabel>
    <relationshipName>Wages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Wages__c/fields/Employer_Tax__c.field-meta.xml
<CustomField>
    <fullName>Employer_Tax__c</fullName>
    <label>Employer Tax %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Wages__c/fields/Employer_Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Employer_Tax_Amount__c</fullName>
    <formula>IF( Compensation__r.Employee__r.RecordType.DeveloperName == &#39;Sales_Employee&#39;, (Employer_Tax__c) * ( Wage_Amount__c + Bonus_Amount__c ), IF(TEXT(Compensation__r.Employee__r.Employee_Type__c) == &#39;Salaried Employee&#39;, (Employer_Tax__c) * ( Wage_Amount__c + Bonus_Amount__c ),0) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employer Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Wages__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Wages</relationshipLabel>
    <relationshipName>Wages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Wages__c/fields/P_L_Date__c.field-meta.xml
<CustomField>
    <fullName>P_L_Date__c</fullName>
    <label>P&amp;L Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Wages__c/fields/Wage_Amount__c.field-meta.xml
<CustomField>
    <fullName>Wage_Amount__c</fullName>
    <label>Wage Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/EmployeeDepartmentAllocationHandler.cls
/*
Description : This class will be used for writing all the functionalities related to Employee_Department_Allocation__c object.
Date Created : 13th June 2019
Change 1 : Namita Choudhary | 24 June 19 | PCPM - 184
*/
public with sharing class EmployeeDepartmentAllocationHandler implements CommonTriggerHandler{
    
    public void BeforeInsert(List<SObject> newItems){
        //PCPM - 184 | Namita
        addErrorsOnEmpDeptAllocationInsertion((List<Employee_Department_Allocation__c>)newItems);
    }
    
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems){
         
    }
    
    public void BeforeDelete(Map<Id, SObject> oldItems){
        //PCPM - 184 | Namita
        addErrorsOnEmpDeptAllocationDeletion((List<Employee_Department_Allocation__c>)oldItems.values());
    }
    
    public void AfterInsert(Map<Id, SObject> newItems){
        reallocatePLAndCash((Map<Id, Employee_Department_Allocation__c>) newItems, null);
    }
    
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems){
        reallocatePLAndCash((Map<Id, Employee_Department_Allocation__c>) newItems, (Map<Id, Employee_Department_Allocation__c>) oldItems);
    }
    
    public void AfterDelete(Map<Id, SObject> oldItems){
    
    }
    
    public void AfterUndelete(Map<Id, SObject> oldItems){
    
    }
    
    public Boolean IsDisabled(){
    return false;
    }
    /* This method is to delete existing P&L allocation and cash allocation and create new P&L allocation and cash allocation 
        newItems : map of Employee_Department_Allocation__c record to its id after changes
        oldItems : map of Employee_Department_Allocation__c record to its id before changes
        @return null
     */

    public static void reallocatePLAndCash(Map<Id, Employee_Department_Allocation__c> newItems, Map<Id, Employee_Department_Allocation__c> oldItems) {
        Boolean isInsert =  oldItems == null;
        List<Wages__c> wageList = new List<Wages__c>();
        List<Expense_PL_Allocation__c> plAllocation = new List<Expense_PL_Allocation__c>();
        List<Expense_Cash_Allocation__c> cashAllocation = new List<Expense_Cash_Allocation__c>();
        Set<String> employeeIdSet = new Set<String>();

        for(Employee_Department_Allocation__c eda : newItems.values()) {
            if(isInsert ||  (eda.Allocation_percentage__c != null && eda.Allocation_percentage__c != oldItems.get(eda.Id).Allocation_percentage__c)) {
                employeeIdSet.add(eda.Employee__c);
            }
        }
        
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.WAGES_OBJECT,'Id, P_L_Date__c,Cash_Date__c,Employee_Number__c,Wage_Amount__c ,Bonus_Amount__c ,'+
        	'Bonus_GL_Account__c , Bonus_Per_Wage__c ,Compensation__c , Employee_Name__c , Employer_Tax__c ,Employer_Tax_Amount__c , Expense_Account__c',Constant.ACTION_TYPE_ACCESS)){
                for(Wages__c wg : [Select Id, P_L_Date__c, 
                                   Cash_Date__c,Employee_Number__c,
                                   Wage_Amount__c ,Bonus_Amount__c ,
                                   Bonus_GL_Account__c , Bonus_Per_Wage__c ,
                                   Compensation__c , Employee_Name__c , Employer_Tax__c ,
                                   Employer_Tax_Amount__c , Expense_Account__c,
                                   (Select Id From Wage_Expense_Allocations__r),
                                   (Select Id From Expense_Cash_Alllocations__r )
                                   From Wages__c
                                   where Employee_Number__c  In: employeeIdSet 
                                   AND P_L_Date__c  >: date.today()]){
                                       wageList.add(wg);
                                       plAllocation.addAll(wg.Wage_Expense_Allocations__r);
                                       cashAllocation.addAll(wg.Expense_Cash_Alllocations__r);
                                   }
        }        
        PlaceCPM_Utility.deleteRecords(plAllocation, CONSTANT.EXPENSE_PL_ALLOCATION_OBJECT, false); //520
        PlaceCPM_Utility.deleteRecords(cashAllocation, CONSTANT.EXPENSE_CASG_ALLOCATION_OBJECT, false); //520
        
        if(wageList != null && wageList.size() > 0) {
            WageTriggerHandler.createPL(wageList,false);
        }
    }
    
    /*
     * Method for before insert event
     * @param : newEmpDeptAlloc - list of new Employee_Department_Allocation__c records
     * return null
     */
    public static void addErrorsOnEmpDeptAllocationInsertion(List<Employee_Department_Allocation__c> newEmpDeptAlloc){
        //PCPM-184
        Map<String, List<String>> mapEmpAndRoleProfile = new Map<String, List<String>>(); 
       	Map<String, Decimal> mapEmpAllocations = new Map<String, Decimal>();        
        
        for(Employee_Department_Allocation__c eda: newEmpDeptAlloc){
            //If(eda.Allocation_Percentage__c != null && eda.Allocation_Percentage__c > 0){ //PCPM-184
            	mapEmpAllocations.put(eda.Employee__c, 0);
            	mapEmpAndRoleProfile.put(eda.Employee__c, new List<String>()); //PCPM-184
        	//}
           
            If(eda.Allocation_Percentage__c == null || eda.Allocation_Percentage__c <= 0){
            	eda.addError(System.Label.EmployeeAllocationErrorLessThan0);
        	} 
        }
        
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.EMPLOYEE_DEPARTMENT_ALLOCATION_OBJECT,'id, Employee__c, Allocation_Percentage__c, Role__c',Constant.ACTION_TYPE_ACCESS)){
            for(Employee_Department_Allocation__c eda: [SELECT id, Employee__c, Allocation_Percentage__c, Role__c 
                                                        FROM Employee_Department_Allocation__c 
                                                        WHERE Employee__c IN: mapEmpAllocations.keySet()]){			
                //PCPM - 184 
                if(eda.Allocation_Percentage__c != null && eda.Allocation_Percentage__c > 0){
                    mapEmpAllocations.put(eda.Employee__c, mapEmpAllocations.get(eda.Employee__c) + eda.Allocation_Percentage__c);
                }
                if(eda.Role__c != null){
                   mapEmpAndRoleProfile.get(eda.Employee__c).add(eda.Role__c);                                            
                }                                           
            }
    	}
        for(Employee_Department_Allocation__c eda: newEmpDeptAlloc){
           if(mapEmpAllocations.containsKey(eda.Employee__c) && mapEmpAllocations.get(eda.Employee__c) + eda.Allocation_Percentage__c > 100){
               eda.addError(System.Label.TotalAllocationPercentageError); //PCPM - 184
           }
            //PCPM - 184
           if(mapEmpAndRoleProfile.containsKey(eda.Employee__c) && eda.Role__c != null && mapEmpAndRoleProfile.get(eda.Employee__c).contains(eda.Role__c)){
               eda.addError(System.Label.EmpRoleProfileError); 
           }
        }
    }
    
    /* PCPM - 184
     * Method for before delete event
     * @param : empDeptAllocList - list of to be deleted Employee_Department_Allocation__c records
     * return null
     */
    public static void addErrorsOnEmpDeptAllocationDeletion(List<Employee_Department_Allocation__c> empDeptAllocList){
        Map<String, Integer> mapEmpAndDeptAllocations = new Map<String, Integer>();
        for(Employee_Department_Allocation__c eda: empDeptAllocList){
            mapEmpAndDeptAllocations.put(eda.Employee__c, 0);
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.EMPLOYEE_DEPARTMENT_ALLOCATION_OBJECT,'id, Employee__c, Allocation_Percentage__c',Constant.ACTION_TYPE_ACCESS)){
            for(Employee_Department_Allocation__c eda: [Select id, Employee__c, Allocation_Percentage__c from Employee_Department_Allocation__c where Employee__c IN: mapEmpAndDeptAllocations.keySet()]){	
                mapEmpAndDeptAllocations.put(eda.Employee__c, mapEmpAndDeptAllocations.get(eda.Employee__c)+1);
            }
    	}
        for(Employee_Department_Allocation__c eda : empDeptAllocList){
            if(eda.Employee__c != Null && mapEmpAndDeptAllocations.containsKey(eda.Employee__c) && mapEmpAndDeptAllocations.get(eda.Employee__c) == 1){
               eda.addError(System.Label.AtleastOneEmpDeptAllocOnEmployee ); 
           }
        }
    }
}