force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/P_L_Category__c/P_L_Category__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Category</label>
    <nameField>
        <label>P&amp;L Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Category__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/P_L_Statement__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Statement</label>
    <nameField>
        <label>P&amp;L Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Statement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Statement__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>P&amp;L Statement</relationshipLabel>
    <relationshipName>P_L_Statement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/P_L_Category__c.field-meta.xml
<CustomField>
    <fullName>P_L_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P&amp;L Category</label>
    <referenceTo>P_L_Category__c</referenceTo>
    <relationshipLabel>P&amp;L Statement</relationshipLabel>
    <relationshipName>P_L_Statement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GLAccountTriggerHandlerTest.cls
/*
Description : This class is test class for GLAccountTriggerHandler.
Date Created : 21th June 2019
*/
@isTest
Private class GLAccountTriggerHandlerTest {
    static GL_Code__c glaccount;
    //  Method to create test data.
    //  @param 
    //  @return void
    static void createTestData(){
        TestUtility.createAssumption(24 , true);
        P_L_Category__c plCategory = TestUtility.createPlCategory('General and Admin','Revenue',True);
        glaccount = TestUtility.createGLCode('Advertising',600,plCategory.id,True);
    }

    //  Method to test insert cases
    //  @param year is the selected year on PAndL component
    //  @return MainWrapper
    static testMethod void testInsert(){
        createTestData();
        // When gl account is inserted its corresponding pl statement should also get inserted with 0 values.
        System.assert([Select id FROM P_L_Statement__c].size() > 0);
    }

    //  Method to test update scenerio
    //  @param 
    //  @return void
    static testMethod void testUpdate(){
        createTestData();
        For(GL_Code__c glc : [Select id , sequence__c from GL_Code__c limit 1]){
            glc.sequence__c = 2;
            glaccount = glc;
        }
        update glaccount;
        System.assert([Select id, sequence__c FROM P_L_Statement__c][0].sequence__c == 1.02);
    }

    //  Method to test delete scenerio
    //  @param 
    //  @return void
    static testMethod void testDelete(){
        createTestData();
        delete glaccount;
        System.assert([Select id FROM P_L_Statement__c where GL_Code__c != Null ].size() == 0);
    }
}