force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/P_L_Category__c/P_L_Category__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Category</label>
    <nameField>
        <label>P&amp;L Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Category__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/P_L_Statement__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Statement</label>
    <nameField>
        <label>P&amp;L Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Statement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Statement__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>P&amp;L Statement</relationshipLabel>
    <relationshipName>P_L_Statement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/P_L_Category__c.field-meta.xml
<CustomField>
    <fullName>P_L_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P&amp;L Category</label>
    <referenceTo>P_L_Category__c</referenceTo>
    <relationshipLabel>P&amp;L Statement</relationshipLabel>
    <relationshipName>P_L_Statement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PLCategoryTriggerHandlerTest.cls
    /*
    Description : This class will be as Test for PLCategoryTriggerHandler.
    Date Created : 21th June 2019
    */
    @isTest
    private class PLCategoryTriggerHandlerTest {
        static P_L_Category__c plcat;
        //  Method to crate Data
        //  @param Null
        //  @return void
        static void createTestData(){
            TestUtility.createAssumption(24 , true);
            plcat = TestUtility.createPlCategory('General and Admin','Revenue',True);
            GL_Code__c glaccount = TestUtility.createGLCode('Advertising',600,plcat.id,True);
        }

        //  Method to test update scenerio
        //  @param Null
        //  @return void
        static testMethod void testUpdate(){
            createTestData();
            For(P_L_Category__c plc : [Select id , sequence__c from P_L_Category__c limit 1]){
                plc.sequence__c = 2;
                plcat = plc;
            }
            update plcat;
            //If pl category sequence udpated then its pl statement sequence should also get update.
            System.assert([Select id, sequence__c FROM P_L_Statement__c][0].sequence__c == 2.01);
        }

        //  Method to test delete scenerio
        //  @param Null
        //  @return MainWrapper
        static testMethod void testDelete(){
            createTestData();
            delete plcat;
            System.assert([Select id FROM P_L_Statement__c where P_L_Category__c != Null ].size() == 0);
        }
    }