force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GL_Code__c/fields/P_L_Category_Sequence__c.field-meta.xml
<CustomField>
    <fullName>P_L_Category_Sequence__c</fullName>
    <formula>PL_Category__r.Sequence__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>P&amp;L Category Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GL_Code__c/fields/PL_Category__c.field-meta.xml
<CustomField>
    <fullName>PL_Category__c</fullName>
    <description>PL_Category__c</description>
    <label>P&amp;L Category</label>
    <referenceTo>P_L_Category__c</referenceTo>
    <relationshipLabel>GL Accounts</relationshipLabel>
    <relationshipName>PL_Category</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/P_L_Category__c/P_L_Category__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Category</label>
    <nameField>
        <label>P&amp;L Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Category__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/P_L_Category__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/P_L_Statement__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Statement</label>
    <nameField>
        <label>P&amp;L Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Statement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Statement__c/fields/April__c.field-meta.xml
<CustomField>
    <fullName>April__c</fullName>
    <defaultValue>0</defaultValue>
    <label>April</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/April_Actual__c.field-meta.xml
<CustomField>
    <fullName>April_Actual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>April Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/August__c.field-meta.xml
<CustomField>
    <fullName>August__c</fullName>
    <defaultValue>0</defaultValue>
    <label>August</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/August_Acutal__c.field-meta.xml
<CustomField>
    <fullName>August_Acutal__c</fullName>
    <defaultValue>0</defaultValue>
    <label>August Acutal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/December__c.field-meta.xml
<CustomField>
    <fullName>December__c</fullName>
    <defaultValue>0</defaultValue>
    <label>December</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/December_Actual__c.field-meta.xml
<CustomField>
    <fullName>December_Actual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>December Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/February__c.field-meta.xml
<CustomField>
    <fullName>February__c</fullName>
    <defaultValue>0</defaultValue>
    <label>February</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/February_Actual__c.field-meta.xml
<CustomField>
    <fullName>February_Actual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>February Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>P&amp;L Statement</relationshipLabel>
    <relationshipName>P_L_Statement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/January__c.field-meta.xml
<CustomField>
    <fullName>January__c</fullName>
    <defaultValue>0</defaultValue>
    <label>January</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/January_Actual__c.field-meta.xml
<CustomField>
    <fullName>January_Actual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>January Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/July__c.field-meta.xml
<CustomField>
    <fullName>July__c</fullName>
    <defaultValue>0</defaultValue>
    <label>July</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/July_Actual__c.field-meta.xml
<CustomField>
    <fullName>July_Actual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>July Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/June__c.field-meta.xml
<CustomField>
    <fullName>June__c</fullName>
    <defaultValue>0</defaultValue>
    <label>June</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/June_Actual__c.field-meta.xml
<CustomField>
    <fullName>June_Actual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>June Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/March__c.field-meta.xml
<CustomField>
    <fullName>March__c</fullName>
    <defaultValue>0</defaultValue>
    <label>March</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/March_Actual__c.field-meta.xml
<CustomField>
    <fullName>March_Actual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>March Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <defaultValue>0</defaultValue>
    <label>May</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/May_Actual__c.field-meta.xml
<CustomField>
    <fullName>May_Actual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>May Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/November__c.field-meta.xml
<CustomField>
    <fullName>November__c</fullName>
    <defaultValue>0</defaultValue>
    <label>November</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/November_Actual__c.field-meta.xml
<CustomField>
    <fullName>November_Actual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>November Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/October__c.field-meta.xml
<CustomField>
    <fullName>October__c</fullName>
    <defaultValue>0</defaultValue>
    <label>October</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/October_Actual__c.field-meta.xml
<CustomField>
    <fullName>October_Actual__c</fullName>
    <defaultValue>0</defaultValue>
    <label>October Actual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/P_L_Category__c.field-meta.xml
<CustomField>
    <fullName>P_L_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P&amp;L Category</label>
    <referenceTo>P_L_Category__c</referenceTo>
    <relationshipLabel>P&amp;L Statement</relationshipLabel>
    <relationshipName>P_L_Statement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/Parent_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Bank Account</label>
    <referenceTo>Payment_Account__c</referenceTo>
    <relationshipLabel>P&amp;L Statement</relationshipLabel>
    <relationshipName>P_L_Statement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/September__c.field-meta.xml
<CustomField>
    <fullName>September__c</fullName>
    <defaultValue>0</defaultValue>
    <label>September</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/September_Acutal__c.field-meta.xml
<CustomField>
    <fullName>September_Acutal__c</fullName>
    <defaultValue>0</defaultValue>
    <label>September Acutal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/Statement_Type__c.field-meta.xml
<CustomField>
    <fullName>Statement_Type__c</fullName>
    <label>Statement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PL</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Category</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
            <value>
                <fullName>Formula</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <label>Payment Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PaymentAccountTriggerHandler.cls
public with sharing class PaymentAccountTriggerHandler implements CommonTriggerHandler{
	public void BeforeInsert(List<SObject> newItems){

    }
    
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems){
        
    }
    
    public void BeforeDelete(Map<Id, SObject> oldItems){
        deletePaymentStatementRecods((Map<Id, Payment_Account__c>) oldItems);
    }
    
    public void AfterInsert(Map<Id, SObject> newItems){
        createBlankStatementRecords((List<Payment_Account__c>)newItems.values());
    }
    
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems){
    }
    
    public void AfterDelete(Map<Id, SObject> oldItems){
        
    }
    
    public void AfterUndelete(Map<Id, SObject> oldItems){
      
    }
    
    public Boolean IsDisabled(){
        return false;
    }
    
    public static void createBlankStatementRecords(List<Payment_Account__c> newItems){
        Integer noOfYears = 0;
        if(PlaceCPM_Utility.assumptionForecastDuration > 0){
            Date dateAfterAssumptionDuration = System.today().addMonths(PlaceCPM_Utility.assumptionForecastDuration);
            noOfYears = dateAfterAssumptionDuration.year();
        }
        P_L_Statement__c pls;
        List<P_L_Statement__c> plStatement = new List<P_L_Statement__c>();
        List<GL_Code__c> glcodeList = new List<GL_Code__c>();
        //Poornima
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.GL_CODE_OBJECT,'Id , PL_Category__c , P_L_Category_Sequence__c , Sequence__c',Constant.ACTION_TYPE_ACCESS)){
        	glcodeList = [SELECT id , PL_Category__c , P_L_Category_Sequence__c , Sequence__c FROM GL_Code__c where PL_Category__c != null];
    	}
        
        Boolean isAccessible = false;
        String fieldsToCheck = 'GL_Code__c, Year__c, P_L_Category__c, Type__c, Sequence__c, January__c, February__c,' +
            				   'March__c, April__c, May__c, June__c, July__c, August__c, September__c, October__c,' +
            					'November__c, December__c, January_Actual__c, February_Actual__c, March_Actual__c,' +
            					'April_Actual__c, May_Actual__c, June_Actual__c, July_Actual__c, August_Acutal__c,' +
            					'September_Acutal__c, October_Actual__c, November_Actual__c, December_Actual__c';
        isAccessible = PlaceCPM_Utility.checkAccessiblityOfFields(Constant.PL_STATEMENT_OBJECT,fieldsToCheck,Constant.ACTION_TYPE_INSERT);
        if(isAccessible){
            for(Integer i= System.today().year() - 1 ; i<=noOfYears ; i++){
                for(Payment_Account__c pa : newItems){
                    for(GL_Code__c glc : glcodeList){
                        pls = new P_L_Statement__c();
                        pls.Statement_Type__c = CONSTANT.EXPCASHTYPE;
                        pls.Parent_Bank_Account__c = pa.Id;
                            pls.GL_Code__c = glc.Id;
                            pls.Year__c = String.valueOf(i);
                            pls.P_L_Category__c = glc.PL_Category__c;
                            pls.Type__c = CONSTANT.PL_STATEMENT_TYPE_CATEGORY;
                        if(glc.P_L_Category_Sequence__c != Null && glc.Sequence__c != Null){
                                pls.Sequence__c =  glc.P_L_Category_Sequence__c + glc.Sequence__c/100;
                        }
                            pls.January__c = 0.0;
                            pls.February__c = 0.0;
                            pls.March__c = 0.0;
                            pls.April__c = 0.0;
                            pls.May__c = 0.0;
                            pls.June__c = 0.0;
                            pls.July__c = 0.0;
                            pls.August__c = 0.0;
                            pls.September__c = 0.0;
                            pls.October__c = 0.0;
                            pls.November__c = 0.0;
                            pls.December__c = 0.0;
                            pls.January_Actual__c= 0.0;
                            pls.February_Actual__c= 0.0;
                            pls.March_Actual__c= 0.0;
                            pls.April_Actual__c= 0.0;
                            pls.May_Actual__c= 0.0;
                            pls.June_Actual__c= 0.0;
                            pls.July_Actual__c= 0.0;
                            pls.August_Acutal__c= 0.0;
                            pls.September_Acutal__c= 0.0;
                            pls.October_Actual__c= 0.0;
                            pls.November_Actual__c= 0.0;
                            pls.December_Actual__c = 0.0;
                        plStatement.add(pls);
                    }
                }
            }
        }
        PlaceCPM_Utility.insertRecords(plStatement, CONSTANT.PL_STATEMENT_OBJECT , false);
    }
    
    public void deletePaymentStatementRecods(Map<Id, Payment_Account__c> oldItems){
        List<P_L_Statement__c> plsListToDelete = new List<P_L_Statement__c>();
        for(P_L_Statement__c pls : [SELECT ID FROM P_L_Statement__c WHERE Statement_Type__c =: CONSTANT.EXPCASHTYPE AND Parent_Bank_Account__c IN : oldItems.keySet()]){
            plsListToDelete.add(pls);
        }
        PlaceCPM_Utility.deleteRecords(plsListToDelete, CONSTANT.PL_STATEMENT_OBJECT, false);
    }
}