force-app/main/default/objects/Quota_Schedule__c/Quota_Schedule__c.object-meta.xml
<CustomObject>
    <label>Quota Schedule</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Quota Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quota Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota_Schedule__c/fields/Monthly_Amount__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Amount__c</fullName>
    <formula>ROUND((Quota_Amount__c/12)/Value(Text(Type__c)),2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/fields/Quota_Amount__c.field-meta.xml
<CustomField>
    <fullName>Quota_Amount__c</fullName>
    <label>Quota Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/fields/Range_End__c.field-meta.xml
<CustomField>
    <fullName>Range_End__c</fullName>
    <label>Range End</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/fields/Range_Start__c.field-meta.xml
<CustomField>
    <fullName>Range_Start__c</fullName>
    <label>Range Start</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Annually</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/Revenue_Contract__c.object-meta.xml
<CustomObject>
    <description>This object captures the revenue Contract.</description>
    <label>Revenue Contract / Statement of Work</label>
    <nameField>
        <displayFormat>RC/SOW - {0000}</displayFormat>
        <label>Revenue Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/QuotaScheduleController.cls
/*
Description : This class is controller to Add Quota Schedule component
Date Created : 11 July 2019
*/
public with sharing class QuotaScheduleController {
    private static List<Revenue_Contract__c> insertedRevenueContacts;  
    public static Map<Id , Quota_Schedule__c> quotaMap;
    public static List<String> typePickListValue = new List<String>();
    public static Map<String , String> typePickListMap = new Map<String , String>();

    static{
        Schema.DescribeFieldResult fieldResult = Quota_Schedule__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple){
            typePickListMap.put(f.getLabel() , f.getValue());
            typePickListValue.add(f.getLabel());
        }
        
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.QUOTA_SCHEDULE_OBJECT,'id , Range_Start__c , Range_End__c , Quota_Amount__c , type__c , Monthly_Amount__c',Constant.ACTION_TYPE_ACCESS)){ 
        	quotaMap = new Map<Id , Quota_Schedule__c>([Select id , Range_Start__c , Range_End__c , Quota_Amount__c , type__c , Monthly_Amount__c  From Quota_Schedule__c where Range_Start__c != null order by Range_Start__c]);
    	}
    }
    
    

    @AuraEnabled
    public static wrapper fetchAllData(){
        return new wrapper();
    }
    
    @AuraEnabled
    public static Quota_Schedule__c addQuotaSchedule(List<Quota_Schedule__c> quotaList) {
        return new Quota_Schedule__c();
    } 

    @AuraEnabled
    public static String createQuotaSchedule(List<Quota_Schedule__c> quotaList  , String typeValue){
        if(typeValue == Null){
            typeValue = typePickListMap.get(typePickListValue[0]);
        }
        For(Quota_Schedule__c qs : quotaList){
            qs.type__c = typeValue;
            if(quotaMap.containsKey(qs.id)){
                quotaMap.remove(qs.id);
            }
        }
        try{
            PlaceCPM_Utility.upsertRecords(quotaList, CONSTANT.QUOTA_SCHEDULE_OBJECT, false); //520
        }
        catch(Exception ex){
            return 'Error : ' + ex.getMessage();
        }
        
        try{
            PlaceCPM_Utility.deleteRecords(quotaMap.values(), CONSTANT.QUOTA_SCHEDULE_OBJECT, false); //520
        }
        catch(Exception ex){
            return 'Error : ' + ex.getMessage();
        }
        
        return 'Success';
    }
    
  //wrapper class to hold the values
    public class wrapper{
        @AuraEnabled public List<Quota_Schedule__c> quotaList;
        @AuraEnabled public Map<String , String> mapOfTypePicklist;
        @AuraEnabled public Integer forecastDuration;
        wrapper(){
            quotaList = quotaMap.values();
            mapOfTypePicklist = typePickListMap;
            forecastDuration = PlaceCPM_Utility.assumptionForecastDuration;
        }
    }
}