force-app/main/default/objects/Expense_Account__c/Expense_Account__c.object-meta.xml
<CustomObject>
    <label>Expense Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Account__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense Accounts</relationshipLabel>
    <relationshipName>Expense_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/fields/P_L_Category__c.field-meta.xml
<CustomField>
    <fullName>P_L_Category__c</fullName>
    <formula>GL_Code__r.PL_Category__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>P&amp;L Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Account</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payment_Account__c</referenceTo>
    <relationshipLabel>Expense Accounts</relationshipLabel>
    <relationshipName>Expense_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/recordTypes/Revenue_Expense.recordType-meta.xml
<RecordType>
    <fullName>Revenue_Expense</fullName>
    <active>true</active>
    <label>Revenue Expense</label>
</RecordType>

force-app/main/default/objects/Expense_Detail__c/Expense_Detail__c.object-meta.xml
<CustomObject>
    <description>Object to Store Time frame and Amount Information related to Expense Account.</description>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>ED - {0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Detail__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense Details</relationshipLabel>
    <relationshipName>Expense_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/Expense_PL_Allocation__c.object-meta.xml
<CustomObject>
    <label>Expense GL Allocation</label>
    <nameField>
        <displayFormat>EPLA-{000000}-{000}</displayFormat>
        <label>Expense P&amp;L Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense GL Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Wage_Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Expense_Detail__c.field-meta.xml
<CustomField>
    <fullName>Expense_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Detail</label>
    <referenceTo>Expense_Detail__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Expense_P_L_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Expense_P_L_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/P_L_Category__c/P_L_Category__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Category</label>
    <nameField>
        <label>P&amp;L Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <label>Payment Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Profit_Loss__c/Profit_Loss__c.object-meta.xml
<CustomObject>
    <label>P&amp;L</label>
    <nameField>
        <label>Profit &amp; Loss Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;Ls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CashControllerTest.cls
@isTest 
public class CashControllerTest {
    static GL_Code__c glCode;
    static GL_Code__c glc;
    static Account account1;
    static Expense_Account__c expAcc;
    static void createTestData(){
        TestUtility.createAssumption(24 , true);
        Profit_Loss__c pl = TestUtility.createPL('Test', Date.today(), date.today(), true);
        P_L_Category__c plCategory = TestUtility.createPlCategory('Test','Expense', true);
        glCode = TestUtility.createGLCode('Test', 500, plCategory.Id, true);
        
        account1 = TestUtility.createAccount('Test vendor1', true);
        Payment_Account__c pa = TestUtility.createPaymentAccount('testPaymentAccount',true);
        expAcc = TestUtility.createExpenseAccount(account1.Id, glCode.Id, '3', false);
        expAcc.Name = 'D-Link';
        expAcc.Payment_Account__c = pa.id;
        insert expAcc;
        
        Expense_Detail__c expDt = TestUtility.createExpenseDetail(expAcc.Id,  date.newInstance(2019,01,01) ,  date.newInstance(2019,12,31) , date.newInstance(2019,01,01) , 1000.00, '0', True);
        Expense_PL_Allocation__c expense = TestUtility.createExpensePlAllocation(glCode.Id, pl.Id, true);   
        
        glc = TestUtility.createGLCode('Test', 100 , plCategory.Id , true);
        
    }
    
    static testMethod void testGetPLStatement(){
        createTestData();
        CashForecastMainController.createTableHeader('Year');
        CashForecastMainController.createTableHeader('Quarter');
        //CashController.parseDateRangeStringAndAssign('{\'2019\':[2,3,4,5,6,7,8,9,10,11,12]}');
        CashForecastMainController.MainWrapper mw = CashForecastMainController.getPLStatement(null , Label.MONTH , null);
        CashForecastMainController.getPLStatementWithFilterAndExpansion(null , Label.MONTH  , mw.dateRange , mw.monthAndYearList , null , mw.yearsTobeFetched , null);
        //mw = CashController.getPLStatement(null ,Label.QUARTER , null);
        //mw = CashController.getPLStatement(null ,Label.YEAR , null);
        CashForecastMainController.getPLStatement(Label.Only_Actual ,Label.MONTH , null);
        CashForecastMainController.getPLStatement(Label.Only_Forecast ,Label.MONTH , null);
        CashForecastMainController.getPLStatement(Label.PLTabVariance ,Label.MONTH , null);
        System.assert(mw.plsWrapper.size() > 0 , 'No statement data');
        CashForecastMainController.addPL(glCode.Id , null , 0 , mw.dateRange , mw.monthAndYearList , Label.MONTH ,  null);
        CashForecastMainController.addPL(glCode.Id , null , 0 , mw.dateRange , mw.monthAndYearList , Label.QUARTER , null);
        CashForecastMainController.addPL(glCode.Id , null , 0 , mw.dateRange , mw.monthAndYearList , Label.YEAR , null);
        CashForecastMainController.applyTimeFrame(Label.MONTH , null , null , null);
        CashForecastMainController.applyTimeFrame(Label.QUARTER , null , null , null);
        CashForecastMainController.applyTimeFrame(Label.YEAR , null , null , null);
        CashForecastMainController.parseFromObject = false;
        //CashForecastMainController.applyTimeFrame(Label.Week , null , null , null);
        CashForecastMainController.applyFiltersPL(1 , 12 , 2019 , 2021 , Label.MONTH , null , null , '1 oct 2019' , '31 oct 2019');
        CashForecastMainController.applyFiltersPL(1 , 12 , 2019 , 2019 , Label.MONTH , null , null , '1 oct 2019' , '31 oct 2019');
        //CashController.applyFiltersPL(1 , 4 , 2019 , 2021 , Label.QUARTER , null);
        //CashController.applyFiltersPL(1 , 12 , 2019 , 2021 , Label.YEAR , null);
        CashForecastMainController.savePL(expAcc.Id , '1' , '100' , false , '2019' , glCode.Id , mw.dateRange , mw.monthAndYearList , null , mw.yearsTobeFetched, null , null , 'Month');
        //CashForecastMainController.savePL(expAcc.Id , '1' , '100' , false , '2019' , glCode.Id , mw.dateRange , mw.monthAndYearList , null , mw.yearsTobeFetched, null , null , 'Week');
        CashForecastMainController.getPLCategoryType(glCode.id);
        CashForecastMainController.getSplitScreenData(expAcc.Id);
    }
    
     static testMethod void readPageLayout(){
        Id recordTypeId = Schema.SObjectType.Expense_Account__c.getRecordTypeInfosByDeveloperName().get('Revenue_Expense').getRecordTypeId();
        CashForecastMainController.getEditPageLayoutSections('Expense_Account__c' , recordTypeId);
        CashForecastMainController.fetchRecordTypeValues('Expense_Account__c');
        PAndLTabController.getDetailPageLayoutSections(PlaceCPM_Utility.getCustomObjOrFieldName('Expense_Account__c') , recordTypeId);
        System.assertNotEquals(null, PAndLTabController.getDetailPageLayoutSections(PlaceCPM_Utility.getCustomObjOrFieldName('Expense_Account__c'), recordTypeId));
    }
}