force-app/main/default/objects/Expense_Account__c/Expense_Account__c.object-meta.xml
<CustomObject>
    <label>Expense Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Account__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense Accounts</relationshipLabel>
    <relationshipName>Expense_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Semi Annually</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Annually</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Account__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expense Accounts</relationshipLabel>
    <relationshipName>Expense_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/Expense_Detail__c.object-meta.xml
<CustomObject>
    <description>Object to Store Time frame and Amount Information related to Expense Account.</description>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>ED - {0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Detail__c/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Auto Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense Details</relationshipLabel>
    <relationshipName>Expense_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/fields/GL_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Id__c</fullName>
    <formula>Expense_Account__r.GL_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GL Account Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/fields/Monthly_Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Expense_Amount__c</fullName>
    <formula>IF(Is_Annual_Amount__c,  Expense_Amount__c / 12, Expense_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Expense Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <formula>Text(Expense_Account__r.Payment_Frequency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/fields/Payment_Term_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_After_Days__c</fullName>
    <label>Payment Term (After # Days)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term_After_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/fields/Vendor_Id__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Id__c</fullName>
    <formula>Expense_Account__r.Vendor__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/Expense_PL_Allocation__c.object-meta.xml
<CustomObject>
    <label>Expense GL Allocation</label>
    <nameField>
        <displayFormat>EPLA-{000000}-{000}</displayFormat>
        <label>Expense P&amp;L Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense GL Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Wage_Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Expense_P_L_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/P_L__c.field-meta.xml
<CustomField>
    <fullName>P_L__c</fullName>
    <label>P&amp;L</label>
    <referenceTo>Profit_Loss__c</referenceTo>
    <relationshipName>Expense_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Expense_P_L_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/Revenue_Account__c.object-meta.xml
<CustomObject>
    <label>Revenue Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Account__c/fields/Billing_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Billing_Cycle__c</fullName>
    <label>Billing Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Semi Annually</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Annually</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Revenue</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Revenue Accounts</relationshipLabel>
    <relationshipName>Revenue_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/Revenue_Contract__c.object-meta.xml
<CustomObject>
    <description>This object captures the revenue Contract.</description>
    <label>Revenue Contract / Statement of Work</label>
    <nameField>
        <displayFormat>RC/SOW - {0000}</displayFormat>
        <label>Revenue Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Contract__c/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Auto Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>This field denotes the Contract End Date</description>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <description>This field denotes the Start Date.</description>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <description>This field denotes the Invoice Date.</description>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Payment_Term_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_After_Days__c</fullName>
    <description>This field denotes the Payment Term (After # Days).</description>
    <label>Payment Term (After # Days)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term_After_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Revenue_Contract__c/fields/Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Account__c</fullName>
    <description>This field denotes the parent Revenue Account.</description>
    <label>Revenue Account</label>
    <referenceTo>Revenue_Account__c</referenceTo>
    <relationshipLabel>Revenue Contract / Statement of Work</relationshipLabel>
    <relationshipName>Revenue_Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Revenue_P_L_Allocation__c/Revenue_P_L_Allocation__c.object-meta.xml
<CustomObject>
    <label>Revenue GL Allocation</label>
    <nameField>
        <displayFormat>RPLA-{000000}-{000}</displayFormat>
        <label>Revenue P&amp;L Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue GL Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_P_L_Allocation__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Revenue GL Allocations</relationshipLabel>
    <relationshipName>Revenue_P_L_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_P_L_Allocation__c/fields/P_L__c.field-meta.xml
<CustomField>
    <fullName>P_L__c</fullName>
    <label>P&amp;L</label>
    <referenceTo>Profit_Loss__c</referenceTo>
    <relationshipLabel>Revenue GL Allocations</relationshipLabel>
    <relationshipName>Revenue_P_L_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Revenue_P_L_Allocation__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <formula>P_L__r.Period_Start_Date__c</formula>
    <label>Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_P_L_Allocation__c/fields/Revenue_Account__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue Account</label>
    <referenceTo>Revenue_Account__c</referenceTo>
    <relationshipLabel>Revenue GL Allocations</relationshipLabel>
    <relationshipName>Revenue_P_L_Allocations_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Term_After_Days.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <default>true</default>
        <label>On Delivery</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Net 15</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Net 30</label>
    </customValue>
    <customValue>
        <fullName>45</fullName>
        <label>Net 45</label>
    </customValue>
    <customValue>
        <fullName>60</fullName>
        <label>Net 60</label>
    </customValue>
    <customValue>
        <fullName>75</fullName>
        <label>Net 75</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>Net 90</label>
    </customValue>
    <masterLabel>Payment Term (After # Days)</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/placeCPM_CustomExpenseRevenueIterable.cls
/*
 Created Date :  19 June 2019
 Class Name   :  placeCPM_CustomExpenseRevenueIterable
 Description  :  PCPM-67 & 72 | Custom Iterable class for Expense and Revenue Accounts  

 Change 1     :
*/

public with sharing class placeCPM_CustomExpenseRevenueIterable implements Iterator<SObject>{
	public List<SObject> sobjs {get; set;} 
    Integer i {get; set;} 
    
    public placeCPM_CustomExpenseRevenueIterable(){
        sobjs = new List<SObject>();
        
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.expenseAccountObject,'ID ,Payment_Frequency__c',Constant.ACTION_TYPE_ACCESS) &&
           PlaceCPM_Utility.checkAccessiblityOfFields(Constant.EXPENSE_DETAIL_OBJECT,'id , Start_Date__c, End_Date__c,Auto_Renew__c,Invoice_Date__c,Payment_Frequency__c,'+
           'GL_Account_Id__c,Vendor_Id__c,Monthly_Expense_Amount__c,Payment_Term_After_Days__c',Constant.ACTION_TYPE_ACCESS) &&
           PlaceCPM_Utility.checkAccessiblityOfFields(Constant.expenseAccountObject,'ID ,Payment_Frequency__c,Vendor__c',Constant.ACTION_TYPE_ACCESS)){
            for( Expense_Account__c expDetailAcc : [SELECT ID ,Payment_Frequency__c,
                                                           (SELECT id , Start_Date__c, End_Date__c, 
                                                                    Auto_Renew__c,Invoice_Date__c,Payment_Frequency__c, 
                                                                    Expense_Account__r.Id , Expense_Account__r.Vendor__c , 
                                                                    GL_Account_Id__c,Vendor_Id__c,Monthly_Expense_Amount__c,
                                                                    Payment_Term_After_Days__c From Expense_Details__r 
                                                                    WHERE Start_Date__c != null AND 
                                                                    (End_Date__c = null OR (End_Date__c != null AND Auto_Renew__c = true))                          
                                                                    ORDER BY Start_Date__c DESC LIMIT 1),
                                                            (SELECT Id, P_L__r.Period_Start_Date__c, P_L__c FROM 
                                                                     Wage_Expense_Allocations__r 
                                                                     ORDER BY P_L__r.Period_Start_Date__c DESC LIMIT 1)                                                                 
                                                            FROM Expense_Account__c]) {
                sobjs.add(expDetailAcc);
           }
    	} 
       if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.revenueAccountObject,'ID , GL_Code__c , Billing_Cycle__c',Constant.ACTION_TYPE_ACCESS) &&
          PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_CONTRACT_OBJECT,'id,Contract_Start_Date__c,Contract_End_Date__c,Revenue_Account__c, Auto_Renew__c, Contract_Months__c,Invoice_Date__c,Payment_Term_After_Days__c,Total_Monthly_Revenue__c',Constant.ACTION_TYPE_ACCESS) && 
          PlaceCPM_Utility.checkAccessiblityOfFields(Constant.REVENUE_PL_ALLOCATION_OBJECT,'Id, Period_Start_Date__c',Constant.ACTION_TYPE_ACCESS)){
       for( Revenue_Account__c revenueAccount : [SELECT ID , GL_Code__c , Billing_Cycle__c,
                                                            (SELECT id,Contract_Start_Date__c,Contract_End_Date__c,
                                                                    Revenue_Account__c, Auto_Renew__c, Contract_Months__c,
                                                                    Invoice_Date__c,Payment_Term_After_Days__c,
                                                                    Total_Monthly_Revenue__c From 
                                                                    Revenue_Contracts__r 
                                                                    WHERE Contract_Start_Date__c != null AND
                                                                    (Contract_End_Date__c  = null OR (Contract_End_Date__c  != null AND Auto_Renew__c=true))
                                                                    ORDER BY Contract_Start_Date__c desc limit 1),
                                                             (SELECT Id, Period_Start_Date__c 
                                                                    FROM Revenue_P_L_Allocations_del__r  
                                                                    ORDER BY Period_Start_Date__c desc limit 1)
                                                             FROM Revenue_Account__c] ) {
            sobjs.add(revenueAccount);
       }
    }
       i = 0; 
   }   
   public boolean hasNext(){ 
       if(i >= sobjs.size()) 
           return false; 
       else 
           return true; 
   }    
   public SObject next(){ 
       if(i == sobjs.size()){return null;} 
       i++; 
       return sobjs[i-1];
   } 
}