force-app/main/default/objects/Expense_Account__c/Expense_Account__c.object-meta.xml
<CustomObject>
    <label>Expense Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Account__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense Accounts</relationshipLabel>
    <relationshipName>Expense_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/fields/P_L_Category__c.field-meta.xml
<CustomField>
    <fullName>P_L_Category__c</fullName>
    <formula>GL_Code__r.PL_Category__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>P&amp;L Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Account</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payment_Account__c</referenceTo>
    <relationshipLabel>Expense Accounts</relationshipLabel>
    <relationshipName>Expense_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/recordTypes/Revenue_Expense.recordType-meta.xml
<RecordType>
    <fullName>Revenue_Expense</fullName>
    <active>true</active>
    <label>Revenue Expense</label>
</RecordType>

force-app/main/default/objects/Expense_Detail__c/Expense_Detail__c.object-meta.xml
<CustomObject>
    <description>Object to Store Time frame and Amount Information related to Expense Account.</description>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>ED - {0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Detail__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense Details</relationshipLabel>
    <relationshipName>Expense_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/Expense_PL_Allocation__c.object-meta.xml
<CustomObject>
    <label>Expense GL Allocation</label>
    <nameField>
        <displayFormat>EPLA-{000000}-{000}</displayFormat>
        <label>Expense P&amp;L Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense GL Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Wage_Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Expense_Detail__c.field-meta.xml
<CustomField>
    <fullName>Expense_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Detail</label>
    <referenceTo>Expense_Detail__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Expense_P_L_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Expense_P_L_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bonus</fullName>
            </value>
            <value>
                <fullName>Payroll Tax</fullName>
            </value>
            <value>
                <fullName>Wage</fullName>
            </value>
            <value>
                <fullName>Expense Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/P_L_Category__c/P_L_Category__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Category</label>
    <nameField>
        <label>P&amp;L Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Category__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/P_L_Statement__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Statement</label>
    <nameField>
        <label>P&amp;L Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Statement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Statement__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>P&amp;L Statement</relationshipLabel>
    <relationshipName>P_L_Statement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/P_L_Category__c.field-meta.xml
<CustomField>
    <fullName>P_L_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P&amp;L Category</label>
    <referenceTo>P_L_Category__c</referenceTo>
    <relationshipLabel>P&amp;L Statement</relationshipLabel>
    <relationshipName>P_L_Statement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P_L_Statement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Category</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
            <value>
                <fullName>Formula</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <label>Payment Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Profit_Loss__c/Profit_Loss__c.object-meta.xml
<CustomObject>
    <label>P&amp;L</label>
    <nameField>
        <label>Profit &amp; Loss Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;Ls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PAndLTabControllerTest.cls
@isTest 
public class PAndLTabControllerTest {
    static GL_Code__c glCode;
    static GL_Code__c glc;
    static Account account1;
    static Expense_Account__c expAcc;
    static void createTestData(){
        TestUtility.createAssumption(24,true);
        Profit_Loss__c pl = TestUtility.createPL('Test', Date.today(), date.today(), true);
        P_L_Category__c plCategory = TestUtility.createPlCategory('Test','Expense', true);
        glCode = TestUtility.createGLCode('Test', 500, plCategory.Id, true);
        
        account1 = TestUtility.createAccount('Test vendor1', true);
        Payment_Account__c pa = TestUtility.createPaymentAccount('testPaymentAccount',true);
        
        expAcc = TestUtility.createExpenseAccount(account1.Id, glCode.Id, '3', false);
        expAcc.Name = 'D-Link';
        expAcc.Payment_Account__c = pa.id;
        insert expAcc;
        
        Expense_Detail__c expDt = TestUtility.createExpenseDetail(expAcc.Id,  date.newInstance(2019,01,01) ,  date.newInstance(2019,12,31) , date.newInstance(2019,01,01) , 1000.00, '0', True);
        Expense_PL_Allocation__c expense = TestUtility.createExpensePlAllocation(glCode.Id, pl.Id, true);   
        System.assert([Select id from P_L_Statement__c].size() > 0 , '');
        
        glc = TestUtility.createGLCode('Test', 100 , plCategory.Id , true);
        List<P_L_Statement__c> plsStatementList = new List<P_L_Statement__c>();
        P_L_Statement__c pls = new P_L_Statement__c();
        pls.P_L_Category__c = plCategory.Id;
        pls.GL_Code__c = glc.Id;
        pls.type__c = CONSTANT.PL_STATEMENT_TYPE_TOTAL;
        pls.Year__c = '2019';
        plsStatementList.add(pls);
        pls = new P_L_Statement__c();
        pls.P_L_Category__c = plCategory.Id;
        pls.GL_Code__c = glc.Id;
        pls.type__c = CONSTANT.PL_STATEMENT_TYPE_CATEGORY;
        pls.Year__c = '2019';
        plsStatementList.add(pls);
        pls = new P_L_Statement__c();
        pls.P_L_Category__c = plCategory.Id;
        pls.GL_Code__c = glc.Id;
        pls.type__c = CONSTANT.PL_STATEMENT_TYPE_TOTAL;
        pls.Year__c = '2019';
        plsStatementList.add(pls);
        insert plsStatementList;
    }
    
    static testMethod void testGetPLStatement(){
        createTestData();
        PAndLTabController.MainWrapper mw = PAndLTabController.getPLStatement(null ,Label.MONTH , null);
        PAndLTabController.getPLStatementWithFilterAndExpansion(null , Label.MONTH  , mw.dateRange , mw.monthAndYearList ,  new List<Integer>{0} , mw.yearsTobeFetched);
        mw = PAndLTabController.getPLStatement(null ,Label.QUARTER , null);
        mw = PAndLTabController.getPLStatement(null ,Label.YEAR , null);
        PAndLTabController.getPLStatement(Label.Only_Actual ,Label.MONTH , null);
        PAndLTabController.getPLStatement(Label.Only_Forecast ,Label.MONTH , null);
        PAndLTabController.getPLStatement(Label.PLTabVariance ,Label.MONTH , null);
        System.assert(mw.plsWrapper.size() > 0 , 'No statement data');
        PAndLTabController.addPL(glCode.Id , null , 0 , mw.dateRange , mw.monthAndYearList , Label.MONTH);
        PAndLTabController.addPL(glCode.Id , null , 0 , mw.dateRange , mw.monthAndYearList , Label.QUARTER);
        PAndLTabController.addPL(glCode.Id , null , 0 , mw.dateRange , mw.monthAndYearList , Label.YEAR);
        PAndLTabController.applyTimeFrame(Label.MONTH , null , null);
        PAndLTabController.applyTimeFrame(Label.QUARTER , null , null);
        PAndLTabController.applyTimeFrame(Label.YEAR , null , null);
        PAndLTabController.applyFiltersPL(1 , 12 , 2019 , 2021 , Label.MONTH , null);
        PAndLTabController.applyFiltersPL(1 , 12 , 2019 , 2019 , Label.MONTH , null);
        PAndLTabController.applyFiltersPL(1 , 4 , 2019 , 2021 , Label.QUARTER , null);
        PAndLTabController.applyFiltersPL(1 , 12 , 2019 , 2021 , Label.YEAR , null);
        PAndLTabController.savePL(expAcc.Id , '1' , '100' , false , '2019' , glCode.Id , mw.dateRange , mw.monthAndYearList , new List<Integer>{0} , mw.yearsTobeFetched , null);
        PAndLTabController.createAllocations(expAcc.Id ,glCode.Id , '1' ,'2019', '100' , false );
        PAndLTabController.saveAllocation(mw.dateRange , mw.monthAndYearList , new List<Integer>{0} , mw.yearsTobeFetched);
        PAndLTabController.getPLCategoryType(glCode.Id);
        PAndLTabController.getSplitScreenData(expAcc.Id);
    }

    static testMethod void testPLAndCashAllocationScheduler(){
        Test.startTest();
        String sch = '0  00 1 3 * ?';
        placeCPM_SchedulePLAndCashAllocations sh1 = new placeCPM_SchedulePLAndCashAllocations();
        system.schedule('TestplaceCPM_SchedulePLAndCashAllocations', sch, sh1);
        Test.stopTest();
        
        //Assert
        System.assertNotEquals(null, sh1);
    }
    
    static testMethod void testPLAndCashControllerRemainingMethods(){
        createTestData();
        Test.startTest();
        PAndLTabController.removeAcc(null);
        PAndLTabController.removeAcc(glc.id);
        PAndLTabController.removeAcc(glc.id);
        System.assertNotEquals(null, glc);
        Test.stopTest();
    }
    static testMethod void removeAcc(){
        createTestData();
        Test.startTest();
        PAndLTabController.removeAcc(null);
        PAndLTabController.removeAcc(glc.id);
        PAndLTabController.removeAcc(glc.id);
        System.assertNotEquals(null, glc);        
        Test.stopTest();
    }
     static testMethod void readPageLayout(){
        Id recordTypeId = Schema.SObjectType.Expense_Account__c.getRecordTypeInfosByDeveloperName().get('Revenue_Expense').getRecordTypeId();
        PAndLTabController.getEditPageLayoutSections('Expense_Account__c' , recordTypeId);
        PAndLTabController.fetchRecordTypeValues('Expense_Account__c');
        System.assertNotEquals(null, PAndLTabController.getDetailPageLayoutSections(PlaceCPM_Utility.getCustomObjOrFieldName('Expense_Account__c') , recordTypeId));
    }
}