force-app/main/default/objects/Assumption__c/Assumption__c.object-meta.xml
<CustomObject>
    <label>Assumption</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assumptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assumption__c/fields/Average_License_Price__c.field-meta.xml
<CustomField>
    <fullName>Average_License_Price__c</fullName>
    <label>Average License Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Contract_Period__c.field-meta.xml
<CustomField>
    <fullName>Contract_Period__c</fullName>
    <label>Contract Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Forecasting_Quota__c.field-meta.xml
<CustomField>
    <fullName>Forecasting_Quota__c</fullName>
    <label>Forecasting Quota %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>Revenue_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Revenue</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Assumptions</relationshipLabel>
    <relationshipName>Assumptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>Comp - {00000}</displayFormat>
        <label>Compensation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compensation__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Compensations</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compensation__c/recordTypes/Sales_Employee_Compensation.recordType-meta.xml
<RecordType>
    <fullName>Sales_Employee_Compensation</fullName>
    <active>true</active>
    <label>Sales Employee Compensation</label>
</RecordType>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organization</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Employee_Status__c.field-meta.xml
<CustomField>
    <fullName>Employee_Status__c</fullName>
    <label>Employee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Future Hire</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Role</label>
    <referenceTo>Role__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/Expense_Account__c.object-meta.xml
<CustomObject>
    <label>Expense Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Account__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense Accounts</relationshipLabel>
    <relationshipName>Expense_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/fields/P_L_Category__c.field-meta.xml
<CustomField>
    <fullName>P_L_Category__c</fullName>
    <formula>GL_Code__r.PL_Category__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>P&amp;L Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/recordTypes/General.recordType-meta.xml
<RecordType>
    <fullName>General</fullName>
    <active>true</active>
    <label>General</label>
</RecordType>

force-app/main/default/objects/Expense_Allocation__c/Expense_Allocation__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Expense Allocation</label>
    <nameField>
        <displayFormat>EAN-{00000}</displayFormat>
        <label>Expense Allocation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Allocation__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Expense Allocations</relationshipLabel>
    <relationshipName>Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Allocation__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Expense Allocations</relationshipLabel>
    <relationshipName>Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Allocation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role</label>
    <referenceTo>Role__c</referenceTo>
    <relationshipLabel>Expense Allocations</relationshipLabel>
    <relationshipName>Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/Expense_Detail__c.object-meta.xml
<CustomObject>
    <description>Object to Store Time frame and Amount Information related to Expense Account.</description>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>ED - {0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Detail__c/fields/Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>Revenue_GL_Account__c</fullName>
    <formula>CASESAFEID(Expense_Account__r.GL_Account_Revenue__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Revenue GL Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/recordTypes/Recurring.recordType-meta.xml
<RecordType>
    <fullName>Recurring</fullName>
    <active>true</active>
    <description>This record type represents the Recurring record type.</description>
    <label>Recurring</label>
</RecordType>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/P_L_Category__c/P_L_Category__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Category</label>
    <nameField>
        <label>P&amp;L Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Category__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota__c/Quota__c.object-meta.xml
<CustomObject>
    <label>Quota</label>
    <nameField>
        <displayFormat>QTA-{MMDDYYYY}-{00}</displayFormat>
        <label>Quota Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quota</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Quota</relationshipLabel>
    <relationshipName>Quota</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Quota_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quota Schedule</label>
    <referenceTo>Quota_Schedule__c</referenceTo>
    <relationshipLabel>Quota</relationshipLabel>
    <relationshipName>Quota</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>Revenue_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Quota</relationshipLabel>
    <relationshipName>Quota</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/Quota_Schedule__c.object-meta.xml
<CustomObject>
    <label>Quota Schedule</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Quota Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quota Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota_Schedule__c/fields/Range_End__c.field-meta.xml
<CustomField>
    <fullName>Range_End__c</fullName>
    <label>Range End</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/fields/Range_Start__c.field-meta.xml
<CustomField>
    <fullName>Range_Start__c</fullName>
    <label>Range Start</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Annually</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EmployeeTriggerHandlerTest.cls
@isTest 
public class EmployeeTriggerHandlerTest {
    static testmethod void testQuotaMethod(){
        Account acc = TestUtility.createAccount('TestAccount',True);
        P_L_Category__c plCategory = TestUtility.createPlCategory('General and Admin','Revenue',True);
        GL_Code__c glaccount = TestUtility.createGLCode('Recurring',600,plCategory.id,True);
        
        
        Assumption__c ass = TestUtility.createAssumption(24, true);
        ass.Average_License_Price__c = 345;
        ass.Contract_Period__c = 12;
        ass.Forecasting_Quota__c = 56;
        ass.Revenue_GL_Account__c = glaccount.id;
        update ass;
        
 		Quota_Schedule__c qs = new Quota_Schedule__c();
        qs.Type__c = '3';
        qs.Range_End__c = 1;
        qs.Range_Start__c = 1;
        insert qs;
        
        Organisation__c organisation = TestUtility.createOrganisation('Place Technology', true); 
        Department__c department = TestUtility.createDepartment('SFDC', organisation.Id, glaccount.Id, true);  
        Role__c role = TestUtility.createRole('Tester', department.Id ,true);
        Employee__c emp = TestUtility.createEmployee('TestEmployee',role.Id,System.today(),'Austin','Salaried Employee',CONSTANT.EMPLOYEE_SALES_RT,true);
       
        Quota__c quotaRec = TestUtility.createQuota(emp.Id , 100 , System.today() , System.today().addDays(365) , glaccount.Id , true);
		
        System.assert([select id from Quota__c].size()  > 0);
        
        emp.Employee_Status__c = 'Terminated';
        update emp;
        delete emp;       
    }
    static testmethod void testEmployeeMethod(){
        Account acc = TestUtility.createAccount('TestAccount',True);
        P_L_Category__c plCategory = TestUtility.createPlCategory('General and Admin','Expense',True);
        GL_Code__c glaccount = TestUtility.createGLCode('Advertising',600,plCategory.id,True);
        Organisation__c organisation = TestUtility.createOrganisation('Place Technology', true); 
        Department__c department = TestUtility.createDepartment('SFDC', organisation.Id, glaccount.Id, true);  
        Role__c role = TestUtility.createRole('Tester', department.Id ,false);
        role.Is_Quota_Applicable__c = true;
        insert role;
        Quota_Schedule__c quotaScheduleRec = new Quota_Schedule__c();
        quotaScheduleRec.Type__c = '1'; 
        quotaScheduleRec.Range_Start__c = 1; 
        quotaScheduleRec.Range_End__c = 2;
        insert quotaScheduleRec;
        
        Expense_Account__c expenseAcc = TestUtility.createExpenseAccount(acc.Id, glaccount.Id,'1', true);
        Expense_Detail__C expDetail = TestUtility.createExpenseDetail(expenseAcc.Id, System.Today().addDays(50), System.Today().addDays(300), System.Today().addDays(50),  100.00, '0', true);
        
        Expense_Allocation__c expenseAlloc = TestUtility.createExpenseAllocation(expenseAcc.Id, false);
        expenseAlloc.Role__c  = role.Id;
        expenseAlloc.Department__c = department.Id; 
        expenseAlloc.Organisation__c = organisation.Id;
        insert expenseAlloc;  
        
        Test.startTest();
        Employee__c emp = TestUtility.createEmployee('TestEmployee',role.Id, date.newinstance(2019, 6, 1),'Austin','Salaried Employee',CONSTANT.EMPLOYEE_SALES_RT,true);
        System.assert(true,[Select Id from Quota__c where Employee__c  =: emp.Id].size() > 0);
        emp.Employee_Start_Date__c = emp.Employee_Start_Date__c.addDays(1);
        emp.Expense_Account__c = expenseAcc.Id;
        emp.Employee_Status__c = 'Active';
        emp.Name = 'Test Employee 1';
        update emp;
        Compensation__c com = TestUtility.createCompensation(date.newinstance(2019, 6, 3),date.newinstance(2019, 6, 30),emp.id, 10,'Monthly', null,False);
        com.RecordTypeId = PlaceCPM_Utility.getRecordTypeIdbyDeveloperName('Compensation__c','Sales_Employee_Compensation');
        insert com;
        Wages__c wage = TestUtility.createWages(date.newinstance(2019, 6, 13), date.newinstance(2019, 6, 15), emp.Id, 1200 ,com.Id , 1300, 13000, false);
        wage.Employee_Number__c = emp.Id;
        insert wage;
        
        Test.stopTest();
     }
     static testMethod void testEmployeeUpdate(){
        P_L_Category__c plCategory = TestUtility.createPlCategory('General and Admin','Expense',True);
        GL_Code__c glaccount = TestUtility.createGLCode('Advertising',600,plCategory.id,True);
        Organisation__c organisation = TestUtility.createOrganisation('Place Technology', true); 
        Department__c department = TestUtility.createDepartment('SFDC', organisation.Id, glaccount.Id, true);  
        Role__c role = TestUtility.createRole('Tester', department.Id ,false);
        role.Is_Quota_Applicable__c = true;
        insert role;
        Id comSalesRecordTypeId = PlaceCPM_Utility.getRecordTypeIdbyDeveloperName('Compensation__c','Sales_Employee_Compensation');
        Employee__c employeeRec = TestUtility.createEmployee('TestEmployee',role.Id,date.newinstance(2019, 6, 1),'Austin','Salaried Employee',CONSTANT.EMPLOYEE_SALES_RT,true);
        Compensation__c com = TestUtility.createCompensation(date.newinstance(2019, 6, 1),date.newinstance(2019, 6, 30),employeeRec.id, 10,'Monthly', null,False);
        com.RecordTypeId = comSalesRecordTypeId;
        insert com;
        employeeRec.Employee_Status__c = 'Terminated';
        update employeeRec; 
        
        System.assertEquals(System.today(), [Select End_Date__c  from Compensation__c where Employee__c  =: employeeRec.Id].End_Date__c);
    }    
    
}