force-app/main/default/objects/Assumption__c/Assumption__c.object-meta.xml
<CustomObject>
    <label>Assumption</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assumptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assumption__c/fields/Average_License_Price__c.field-meta.xml
<CustomField>
    <fullName>Average_License_Price__c</fullName>
    <label>Average License Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Contract_Period__c.field-meta.xml
<CustomField>
    <fullName>Contract_Period__c</fullName>
    <label>Contract Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Forecasting_Quota__c.field-meta.xml
<CustomField>
    <fullName>Forecasting_Quota__c</fullName>
    <label>Forecasting Quota %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>Revenue_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Revenue</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Assumptions</relationshipLabel>
    <relationshipName>Assumptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organization</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Is_Quota_Applicable__c.field-meta.xml
<CustomField>
    <fullName>Is_Quota_Applicable__c</fullName>
    <formula>Role__r.Is_Quota_Applicable__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Quota Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Role</label>
    <referenceTo>Role__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Category__c/P_L_Category__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Category</label>
    <nameField>
        <label>P&amp;L Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Category__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota__c/Quota__c.object-meta.xml
<CustomObject>
    <label>Quota</label>
    <nameField>
        <displayFormat>QTA-{MMDDYYYY}-{00}</displayFormat>
        <label>Quota Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quota</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Quota</relationshipLabel>
    <relationshipName>Quota</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Monthly_Quota_Amount__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Quota_Amount__c</fullName>
    <label>Monthly Quota Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Quota_Schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quota Schedule</label>
    <referenceTo>Quota_Schedule__c</referenceTo>
    <relationshipLabel>Quota</relationshipLabel>
    <relationshipName>Quota</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>Revenue_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Quota</relationshipLabel>
    <relationshipName>Quota</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/Quota_Schedule__c.object-meta.xml
<CustomObject>
    <label>Quota Schedule</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Quota Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quota Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota_Schedule__c/fields/Monthly_Amount__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Amount__c</fullName>
    <formula>ROUND((Quota_Amount__c/12)/Value(Text(Type__c)),2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/fields/Quota_Amount__c.field-meta.xml
<CustomField>
    <fullName>Quota_Amount__c</fullName>
    <label>Quota Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/fields/Range_End__c.field-meta.xml
<CustomField>
    <fullName>Range_End__c</fullName>
    <label>Range End</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/fields/Range_Start__c.field-meta.xml
<CustomField>
    <fullName>Range_Start__c</fullName>
    <label>Range Start</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota_Schedule__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Annually</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Role__c/fields/Is_Quota_Applicable__c.field-meta.xml
<CustomField>
    <fullName>Is_Quota_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Quota Applicable?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuotaScheduleTriggerHandlerTest.cls
/*
Description : Test class for QuotaScheduleTrigger
Date Created : 2nd July 2019
Change 1 :  PCPM-235 | Namita | 12 July
*/
@isTest
public class QuotaScheduleTriggerHandlerTest {
    static List<Quota_Schedule__c> quotaScheduleList;
    //PCPM-235
    static Organisation__c organisation;
    static GL_Code__c glaccount;
    static Role__c role;
    
    static void testSetup(){
        Assumption__c assumption = TestUtility.createAssumption(24 , false);
        assumption.Forecasting_Quota__c = 80;
        assumption.Average_License_Price__c = 105;
        assumption.Contract_Period__c = 12;
        insert assumption;
        
        P_L_Category__c plCategory = TestUtility.createPlCategory('Revenue','Revenue',True);
        glaccount = TestUtility.createGLCode('Recurring',600,plCategory.id,True);
        assumption.Revenue_GL_Account__c = glaccount.Id;
        update assumption;
        
        //PCPM-235
        organisation = TestUtility.createOrganisation('Place Technology', true); 
        Department__c department = TestUtility.createDepartment('SFDC', organisation.Id, glaccount.Id, true);  
        role = TestUtility.createRole('Tester', department.Id ,false);
        role.Is_Quota_Applicable__c = true;
        insert role;
        
        PlaceCPM_Utility.getAssumption();
        //PCPM-235
        Employee__c emp = TestUtility.createEmployee('TestEmployee',role.Id , System.today() ,'Austin','Salaried Employee',CONSTANT.EMPLOYEE_SALES_RT,True);
        
        quotaScheduleList = new List<Quota_Schedule__c>();
        Quota_Schedule__c qs = new Quota_Schedule__c();
        qs.Range_Start__c = 1;
        qs.Range_End__c = 2;
        qs.Quota_Amount__c = 100000;
        qs.type__c = String.valueOf(3);
        quotaScheduleList.add(qs);
        qs = new Quota_Schedule__c();
        qs.Range_Start__c = 2;
        qs.Range_End__c = 3;
        qs.Quota_Amount__c = 150000;
        qs.type__c = String.valueOf(3);
        quotaScheduleList.add(qs);
        qs = new Quota_Schedule__c();
        qs.Range_Start__c = 3;
        qs.Range_End__c = 5;
        qs.Quota_Amount__c = 200000;
        qs.type__c = String.valueOf(3);
        quotaScheduleList.add(qs);
        qs = new Quota_Schedule__c();
        qs.Range_Start__c = 5;
        qs.Quota_Amount__c = 250000;
        quotaScheduleList.add(qs);
        qs.type__c = String.valueOf(3);
        insert quotaScheduleList;
    }

    //  Method to test quota schdeule creation                
    //  @param 
    //  @return void
    static testMethod void testQuotaScheduleCreation(){
        testSetup();
        List<quota__c> quotas = [SELECT id FROM quota__c];
        System.assertEquals(quotas.size() , 8);
        quotaScheduleList[1].Quota_Amount__c = 175000;
        update quotaScheduleList[1];
        List<Quota_Schedule__c> qsList = [SELECT id  , Monthly_Amount__c FROM Quota_Schedule__c WHERE Range_Start__c = 2];
        //PCPM-235
        System.assertEquals(qsList[0].Monthly_Amount__c , [SELECT id , Monthly_Quota_Amount__c FROM quota__c where Quota_Schedule__c =: qsList[0].Id][0].Monthly_Quota_Amount__c);
        delete quotaScheduleList;
    }
}