force-app/main/default/objects/Assumption__c/Assumption__c.object-meta.xml
<CustomObject>
    <label>Assumption</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assumptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assumption__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Account</label>
    <referenceTo>Payment_Account__c</referenceTo>
    <relationshipLabel>Assumptions</relationshipLabel>
    <relationshipName>Assumptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/Expense_Account__c.object-meta.xml
<CustomObject>
    <label>Expense Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Account__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense Accounts</relationshipLabel>
    <relationshipName>Expense_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/fields/P_L_Category__c.field-meta.xml
<CustomField>
    <fullName>P_L_Category__c</fullName>
    <formula>GL_Code__r.PL_Category__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>P&amp;L Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Account</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payment_Account__c</referenceTo>
    <relationshipLabel>Expense Accounts</relationshipLabel>
    <relationshipName>Expense_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/recordTypes/General.recordType-meta.xml
<RecordType>
    <fullName>General</fullName>
    <active>true</active>
    <label>General</label>
</RecordType>

force-app/main/default/objects/Expense_Cash_Allocation__c/Expense_Cash_Allocation__c.object-meta.xml
<CustomObject>
    <label>Expense Cash Allocation</label>
    <nameField>
        <displayFormat>ECA-{000000}-{000}</displayFormat>
        <label>Expense Cash Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Cash Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/Cash_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Cash_Forecast__c</fullName>
    <label>Cash Forecast</label>
    <referenceTo>Cash_Forecast__c</referenceTo>
    <relationshipLabel>Expense Cash Allocations</relationshipLabel>
    <relationshipName>Expense_Cash_Alllocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense Cash Allocations</relationshipLabel>
    <relationshipName>Expense_Cash_Alllocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense Cash Allocations</relationshipLabel>
    <relationshipName>Expense_Cash_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <formula>Expense_Account__r.Payment_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/Expense_Detail__c.object-meta.xml
<CustomObject>
    <description>Object to Store Time frame and Amount Information related to Expense Account.</description>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>ED - {0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Detail__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense Details</relationshipLabel>
    <relationshipName>Expense_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/recordTypes/Recurring.recordType-meta.xml
<RecordType>
    <fullName>Recurring</fullName>
    <active>true</active>
    <description>This record type represents the Recurring record type.</description>
    <label>Recurring</label>
</RecordType>

force-app/main/default/objects/Expense_PL_Allocation__c/Expense_PL_Allocation__c.object-meta.xml
<CustomObject>
    <label>Expense GL Allocation</label>
    <nameField>
        <displayFormat>EPLA-{000000}-{000}</displayFormat>
        <label>Expense P&amp;L Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense GL Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Wage_Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Expense_P_L_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/Revenue_Account__c.object-meta.xml
<CustomObject>
    <label>Revenue Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Account__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Revenue</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Revenue Accounts</relationshipLabel>
    <relationshipName>Revenue_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Account</label>
    <referenceTo>Payment_Account__c</referenceTo>
    <relationshipLabel>Revenue Accounts</relationshipLabel>
    <relationshipName>Revenue_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Account__c/recordTypes/General.recordType-meta.xml
<RecordType>
    <fullName>General</fullName>
    <active>true</active>
    <description>Monies brought into the company that is not project driven and can be recurring or non-recurring.</description>
    <label>General</label>
</RecordType>

force-app/main/default/objects/Revenue_Cash_Allocation__c/Revenue_Cash_Allocation__c.object-meta.xml
<CustomObject>
    <label>Revenue Cash Allocation</label>
    <nameField>
        <displayFormat>RCA-{000000}-{000}</displayFormat>
        <label>Revenue Cash Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Cash Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Cash_Allocation__c/fields/Cash_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Cash_Forecast__c</fullName>
    <label>Cash Forecast</label>
    <referenceTo>Cash_Forecast__c</referenceTo>
    <relationshipLabel>Revenue Cash Allocations</relationshipLabel>
    <relationshipName>Revenue_Cash_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Revenue_Cash_Allocation__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Revenue Cash Allocations</relationshipLabel>
    <relationshipName>Revenue_Cash_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Cash_Allocation__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <formula>IF(NOT( ISBLANK(Revenue_Account__c)),IF(NOT( ISBLANK(Revenue_Account__r.Payment_Account__c)), CASESAFEID(Revenue_Account__r.Payment_Account__r.Name), CASESAFEID(Revenue_Account__r.Account_Executive__r.Location__r.Payment_Account__r.Name)), IF(NOT(ISBLANK(Equity__c)),CASESAFEID(Equity__r.Payment_Account__r.Name), null ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Revenue_P_L_Allocation__c/Revenue_P_L_Allocation__c.object-meta.xml
<CustomObject>
    <label>Revenue GL Allocation</label>
    <nameField>
        <displayFormat>RPLA-{000000}-{000}</displayFormat>
        <label>Revenue P&amp;L Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue GL Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_P_L_Allocation__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Revenue GL Allocations</relationshipLabel>
    <relationshipName>Revenue_P_L_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/placeCPM_CreatePLAndCashRecordsTest.cls
/*
Description  : Test Class for placeCPM_CreatePLAndCashRecords
Date Created : 12 JULY 19
Change 1 :  Namita | PCPM-299 | 16 JULY 19
*/
@isTest
public class placeCPM_CreatePLAndCashRecordsTest {
   static Assumption__c assumptionRec;
   static Account acc;
   static List<Profit_Loss__c> listPL;
   static List<Cash_Forecast__c> listCashForecast;
   static Payment_Account__c paymentAcc;
    
    static void createtestData(){
         assumptionRec = TestUtility.createAssumption(1, true); 
         system.debug('assumptionRec=='+assumptionRec);
         acc = TestUtility.createAccount('TestAccount1',True);
         listPL = new List<Profit_Loss__c>();
         listCashForecast = new List<Cash_Forecast__c>();
         Map<Integer,String> mapMonthYear = new Map<Integer,String>();
         mapMonthYear.put(3,'March 2020');
         mapMonthYear.put(4,'April 2020');
         mapMonthYear.put(5,'May 2020');
         mapMonthYear.put(6,'June 2020');
         //mapMonthYear.put(7,'July 2020');
         //mapMonthYear.put(8,'August 2020');
         for(Integer i = 3; i < 7 ; i++){
           Profit_Loss__c pl = TestUtility.createPL(mapMonthYear.get(i),date.newinstance(2020, i, 1),date.newinstance(2020, i, Date.daysInMonth(2020,i)),false);
           Cash_Forecast__c cashForcast = TestUtility.createCashForecast(mapMonthYear.get(i),date.newinstance(2020, i, 1),date.newinstance(2020, i, Date.daysInMonth(2020,i)),false);
           listPL.add(pl);
           listCashForecast.add(cashForcast);
         }
         if(listPL.size()>0){
            insert listPL;
         }
         if(listCashForecast.size() > 0){
            insert listCashForecast;
         }
         paymentAcc = TestUtility.createPaymentAccount('HDFC Bank',true);
    }
    
    @isTest
    public static void testCreatePLAndCashRecords(){
        createtestData();
        P_L_Category__c plCategoryExp = TestUtility.createPlCategory('General and Admin','Expense',true);
        GL_Code__c glaccountExp = TestUtility.createGLCode('Recurring',600,plCategoryExp.id,true);
        Expense_Account__c expenseAcc = TestUtility.createExpenseAccount(acc.Id, glaccountExp.Id, '1', false);
        expenseAcc.Payment_Account__c = paymentAcc.Id;
        insert expenseAcc;
        Expense_Detail__c expenseDetail = TestUtility.createExpenseDetail(expenseAcc.Id, date.newinstance(2020, 7, 1), date.newinstance(2020, 7, 11),date.newinstance(2020, 9, 11), 45000, '30', false);
        expenseDetail.Auto_Renew__c = true;
        insert expenseDetail;
        Expense_PL_Allocation__c expensePLAlloc = new Expense_PL_Allocation__c(Expense_Account__c = expenseAcc.Id,
                                                                               Expense_Detail__c= expenseDetail.Id,
                                                                               GL_Code__c= glaccountExp.Id,
                                                                               P_L__c = listPL[0].Id);
        insert expensePLAlloc;
        Expense_Cash_Allocation__c expenseCashAlloc = new Expense_Cash_Allocation__c(Expense_Account__c = expenseAcc.Id,
                                                                                     Expense_Detail__c= expenseDetail.Id, 
                                                                                     Cash_Forecast__c = listCashForecast[0].Id,
                                                                                     Cash_Date__c = date.newinstance(2020, 7, 21),
                                                                                     Forecast_Amount__c =2000);
        insert expenseCashAlloc;
        
        Test.startTest();
            placeCPM_CreatePLAndCashRecords obj = new placeCPM_CreatePLAndCashRecords();
            Database.executeBatch(obj);
            List<Expense_PL_Allocation__c> expensePLAllocList = [SELECT id, Expense_Account__c,P_L__c FROM Expense_PL_Allocation__c WHERE Expense_Account__c =: expenseAcc.Id];
            List<Expense_Cash_Allocation__c> expenseCashAllocList = [SELECT id, Expense_Account__c FROM Expense_Cash_Allocation__c WHERE Expense_Account__c =: expenseAcc.Id];
            system.assert(expensePLAllocList.size() > 0);
            system.assert(expenseCashAllocList.size() > 0);
        Test.stopTest();
    }
    
    @isTest
    public static void testCreatePLAndCashRecords2(){
        createtestData();
        P_L_Category__c plCategory = TestUtility.createPlCategory('General and Admin','Revenue',true);
        GL_Code__c glaccount = TestUtility.createGLCode('Recurring',600,plCategory.id,true);
        Revenue_Account__c revenueAccount = TestUtility.createRevenueAccount(acc.Id, glaccount.Id, paymentAcc.Id ,'1',false);
        insert revenueAccount;
        Revenue_Contract__c revenueContract = TestUtility.createRevenueContract(revenueAccount.Id, date.newinstance(2020, 7, 1),
                                                            date.newinstance(2020, 8, 31), '30',
                                                            date.newinstance(2020, 7, 11), false);
        revenueContract.Live_Renewed_Date__c = date.newinstance(2020, 8, 21);
        revenueContract.Auto_Renew__c = true;
        insert revenueContract;
        Product__c pdt1 = TestUtility.createProduct('Product 1','Product', 1400,'License',true); 
        Revenue_P_L_Allocation__c  revenuePLAlloc = new Revenue_P_L_Allocation__c (P_L__c = listPL[0].Id, Revenue_Account__c =revenueAccount.Id, Revenue_Contract__c =revenueContract.id, GL_Code__c=glaccount.Id);
        insert revenuePLAlloc;
        Contract_Line_Items__c cli1 = TestUtility.createContractLineItem('CLI 1' ,revenueContract.Id, 1,pdt1.Id, false);
        cli1.Total_Amount__c  = 100;
        insert cli1;
        Revenue_Cash_Allocation__c revenueCashAlloc = new Revenue_Cash_Allocation__c(Revenue_Account__c =revenueAccount.Id,
                                                                                     Revenue_Contract__c =revenueContract.Id,
                                                                                     Cash_Forecast__c = listCashForecast[0].Id,
                                                                                     Cash_Date__c = date.newinstance(2020, 7, 21),
                                                                                     Forecast_Amount__c =2000 );
        
        insert revenueCashAlloc;
        Test.startTest();
            placeCPM_CreatePLAndCashRecords obj = new placeCPM_CreatePLAndCashRecords();
            Database.executeBatch(obj);
            List<Revenue_P_L_Allocation__c> revenuePLAllocList = [SELECT id, Revenue_Account__c,P_L__c FROM Revenue_P_L_Allocation__c WHERE Revenue_Account__c =: revenueAccount.Id];
            List<Revenue_Cash_Allocation__c> revenueCashAllocList = [SELECT id, Revenue_Account__c FROM Revenue_Cash_Allocation__c WHERE Revenue_Account__c =: revenueAccount.Id];
            system.assert(revenuePLAllocList.size() > 0);
            system.assert(revenueCashAllocList.size() > 0);
        Test.stopTest();
    }
}