force-app/main/default/objects/Assumption__c/Assumption__c.object-meta.xml
<CustomObject>
    <label>Assumption</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assumptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assumption__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Account</label>
    <referenceTo>Payment_Account__c</referenceTo>
    <relationshipLabel>Assumptions</relationshipLabel>
    <relationshipName>Assumptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/Expense_Account__c.object-meta.xml
<CustomObject>
    <label>Expense Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Account__c/fields/GL_Account_Revenue__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Revenue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account Revenue</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Revenue</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense Accounts (GL Account Revenue)</relationshipLabel>
    <relationshipName>Expense_Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense Accounts</relationshipLabel>
    <relationshipName>Expense_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/fields/P_L_Category__c.field-meta.xml
<CustomField>
    <fullName>P_L_Category__c</fullName>
    <formula>GL_Code__r.PL_Category__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>P&amp;L Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Account</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Payment_Account__c</referenceTo>
    <relationshipLabel>Expense Accounts</relationshipLabel>
    <relationshipName>Expense_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expense Accounts</relationshipLabel>
    <relationshipName>Expense_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Cash_Allocation__c/Expense_Cash_Allocation__c.object-meta.xml
<CustomObject>
    <label>Expense Cash Allocation</label>
    <nameField>
        <displayFormat>ECA-{000000}-{000}</displayFormat>
        <label>Expense Cash Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Cash Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/Cash_Date__c.field-meta.xml
<CustomField>
    <fullName>Cash_Date__c</fullName>
    <label>Cash Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense Cash Allocations</relationshipLabel>
    <relationshipName>Expense_Cash_Alllocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/Expense_Detail__c.field-meta.xml
<CustomField>
    <fullName>Expense_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Detail</label>
    <referenceTo>Expense_Detail__c</referenceTo>
    <relationshipLabel>Expense Cash Allocations</relationshipLabel>
    <relationshipName>Expense_Cash_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense Cash Allocations</relationshipLabel>
    <relationshipName>Expense_Cash_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/Payment_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Account__c</fullName>
    <formula>Expense_Account__r.Payment_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/Expense_Detail__c.object-meta.xml
<CustomObject>
    <description>Object to Store Time frame and Amount Information related to Expense Account.</description>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>ED - {0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Detail__c/fields/Amount_of_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_Revenue__c</fullName>
    <label>% Amount of Revenue</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense Details</relationshipLabel>
    <relationshipName>Expense_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/Expense_PL_Allocation__c.object-meta.xml
<CustomObject>
    <label>Expense GL Allocation</label>
    <nameField>
        <displayFormat>EPLA-{000000}-{000}</displayFormat>
        <label>Expense P&amp;L Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense GL Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Wage_Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Expense_Detail__c.field-meta.xml
<CustomField>
    <fullName>Expense_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Detail</label>
    <referenceTo>Expense_Detail__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Expense_P_L_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Account</label>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Expense_P_L_Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/P_L__c.field-meta.xml
<CustomField>
    <fullName>P_L__c</fullName>
    <label>P&amp;L</label>
    <referenceTo>Profit_Loss__c</referenceTo>
    <relationshipName>Expense_Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Expense_P_L_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/P_L_Category__c/P_L_Category__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Category</label>
    <nameField>
        <label>P&amp;L Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Category__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <label>Payment Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Profit_Loss__c/Profit_Loss__c.object-meta.xml
<CustomObject>
    <label>P&amp;L</label>
    <nameField>
        <label>Profit &amp; Loss Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;Ls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Profit_Loss__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <label>Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ExpenseAccountDetailTriggerTest.cls
/*
Description : Test Class for ExpenseDetailTriggerHandler and ExpenseAccountDetailTriggerHandler.
Date Created : 
Change 1 :  Namita | PCPM-299 | 16 JULY 19
Change 2 :  Namita | PCPM-304 | 18 JULY 19
*/
@isTest 
public class ExpenseAccountDetailTriggerTest {
    static Account account1;
    static Account account2;
    static P_L_Category__c plCat;
    static GL_Code__c glCode;
    static P_L_Category__c plCat1;
    static GL_Code__c glCode1;
    static List<Expense_Detail__c> expDtList;
    static Expense_Account__c expAcc;

    static testMethod void testExpenseDetail(){
        createData();
        Test.startTest();
            Expense_Detail__c expDt = TestUtility.createExpenseDetail(expAcc.Id, System.today().addDays(200), System.Today().addDays(300), System.Today().addDays(200) , 1000.00, '0', True);
            List<Expense_PL_Allocation__c> plsList = [Select id, P_L__r.Period_Start_Date__c, P_L__r.Period_End_Date__c, Expense_Detail__c from Expense_PL_Allocation__c where Expense_Detail__c =: expDt.id order by P_L__r.Period_Start_Date__c asc];
            List<Expense_Cash_Allocation__c> cshList = [Select id, cash_date__c,  Expense_Detail__c from Expense_Cash_Allocation__c where Expense_Detail__c =: expDt.id order by  cash_date__c asc ];
            System.assert(plsList.size() > 0);
            System.assert(cshList.size() > 0);
        Test.stopTest();
    }
    
    static testMethod void testExpenseDetailUpdate(){
        createData();
        Test.startTest();
            //PCPM-304
            Expense_Account__c expAcc2 = [SELECT Id, Name,Vendor__c,Vendor__r.Name FROM Expense_Account__c WHERE Id = :expAcc.Id];
            System.assert(expAcc2.Name == 'Test vendor1 - D-Link');
            expAcc2.Vendor__c = account2.Id;
            update expAcc2;
            List<Expense_Account__c> expenseAccList = [SELECT Id, Name, Vendor__c,Vendor__r.Name FROM Expense_Account__c WHERE Id =: expAcc.Id]; 
            System.assert(expenseAccList[0].Name == 'Test vendor2 - D-Link');

            Expense_Detail__c expDt = TestUtility.createExpenseDetail(expAcc.Id, System.today().addDays(200), System.Today().addDays(325), System.Today().addDays(200) , 1000.00, '0', True);
            expDt.Expense_Amount__c = 1200;
            List<Expense_PL_Allocation__c> plsList = [Select id, P_L__r.Period_Start_Date__c, P_L__r.Period_End_Date__c, Expense_Detail__c from Expense_PL_Allocation__c where Expense_Detail__c =: expDt.id order by P_L__r.Period_Start_Date__c asc];
            
            Update expDt;
            
            expDt.end_Date__c = System.Today().addDays(275);
        	update expDt;
        
            List<Expense_PL_Allocation__c> plsList1 = [Select id, P_L__r.Period_Start_Date__c, P_L__r.Period_End_Date__c, Expense_Detail__c from Expense_PL_Allocation__c where Expense_Detail__c =: expDt.id order by P_L__r.Period_Start_Date__c asc];
            List<Expense_Cash_Allocation__c> cshList1 = [Select id, cash_date__c,  Expense_Detail__c from Expense_Cash_Allocation__c where Expense_Detail__c =: expDt.id order by  cash_date__c asc ];
            System.assert(plsList.size() > plsList1.size());
        Test.stopTest();
    }
    
    static testMethod void testExpenseDetailDelete(){
        createData();
        Test.startTest();
            Expense_Detail__c expDt = TestUtility.createExpenseDetail(expAcc.Id, System.today().addDays(200), System.Today().addDays(300), System.Today().addDays(200) , 1000.00, '0', True);
            String expDetId = expDt.id;
            delete expDt;
            List<Expense_PL_Allocation__c> plsList = [Select id, P_L__r.Period_Start_Date__c, P_L__r.Period_End_Date__c, Expense_Detail__c from Expense_PL_Allocation__c where Expense_Detail__c =: expDt.id order by P_L__r.Period_Start_Date__c asc];
            List<Expense_Cash_Allocation__c> cshList = [Select id, cash_date__c,  Expense_Detail__c from Expense_Cash_Allocation__c where Expense_Detail__c =: expDt.id order by  cash_date__c asc ];
            System.assert(plsList.size() == 0);
            System.assert(cshList.size() == 0);
            delete expAcc;
        Test.stopTest();
    }
    
    static void createData(){
        Assumption__c aa = TestUtility.createAssumption(24,True);
        account1 = TestUtility.createAccount('Test vendor1', true);
        account2 = TestUtility.createAccount('Test vendor2', true);
        plCat=  TestUtility.createPlCategory('COGS','Expense',True);
        glCode = TestUtility.createGLCode('Advertising', 200, plCat.Id ,True);

        Payment_Account__c pa = TestUtility.createPaymentAccount('testPaymentAccount',true);
        expAcc = TestUtility.createExpenseAccount(account1.Id, glCode.Id, '3', false);
        expAcc.Name = 'D-Link';
        expAcc.Payment_Account__c = pa.id;
        insert expAcc;

        expDtList = new List<Expense_Detail__c>();
        expDtList.add(TestUtility.createExpenseDetail(expAcc.Id, System.Today().addDays(50), System.Today().addDays(300), System.Today().addDays(50),  100.00, '0', false));
        expDtList.add(TestUtility.createExpenseDetail(expAcc.Id, System.Today().addDays(100), System.Today().addDays(350),System.Today().addDays(100), 200.00, '0', false));
        expDtList.add(TestUtility.createExpenseDetail(expAcc.Id, System.Today().addDays(150), System.Today().addDays(400),System.Today().addDays(150), 300.00, '15', false));
        TestUtility.createExpenseDetailList(expDtList, true);
    }

    @isTest
    static void testRecurringRevenue(){
        createData();
        String expDelRevenueRecurringRtId = PlaceCPM_Utility.getRecordTypeIdbyDeveloperName('Expense_Detail__c', CONSTANT.EXPENSE_DETAIL_REVENUE_RECURRING_RT);
        plCat1=  TestUtility.createPlCategory('REVENUE','Revenue',false);
        plCat1.Sequence__c =2;
        insert plCat1;
        glCode1 = TestUtility.createGLCode('Travel', 300, plCat1.Id ,false);
        glCode1.Sequence__c =2;
        insert glCode1;
        Payment_Account__c pa = TestUtility.createPaymentAccount('testPaymentAccount1',true);
        expAcc = TestUtility.createExpenseAccount(account1.Id, glCode.Id, '3', false);
        expAcc.Name = 'D-Link';
        expAcc.Payment_Account__c = pa.id;
        expAcc.GL_Account_Revenue__c = glCode1.id;
        insert expAcc;

         expDtList = new List<Expense_Detail__c>();
        expDtList.add(TestUtility.createExpenseDetail(expAcc.Id, System.Today().addMonths(2), System.Today().addMonths(10), System.Today().addMonths(2),  100.00, '0', false));

        for(Expense_Detail__c expDel : expDtList){
            expDel.Amount_of_Revenue__c = 10;
            expDel.RecordTypeId = expDelRevenueRecurringRtId;
        }
        Test.startTest();
        if(expDtList.size()>0){
            insert expDtList;
        }

         Test.stopTest();
        List<Expense_PL_Allocation__c> plsList = [Select id, P_L__r.Period_Start_Date__c,GL_Code__r.Name, P_L__r.Period_End_Date__c, Expense_Detail__c from Expense_PL_Allocation__c where Expense_Detail__c =: expDtList[0].id order by P_L__r.Period_Start_Date__c asc];
        System.assertEquals('Advertising', plsList[0].GL_Code__r.Name);
     }
}