force-app/main/default/objects/Assumption__c/Assumption__c.object-meta.xml
<CustomObject>
    <label>Assumption</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assumptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assumption__c/fields/Forecast_Duration__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Duration__c</fullName>
    <description>In Months</description>
    <label>Forecast Duration</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/P_L_Category__c/P_L_Category__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Category</label>
    <nameField>
        <label>P&amp;L Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreatePostDeploymentDataTest.cls
@isTest
public class CreatePostDeploymentDataTest {
       /* static testMethod void testCreateData(){
            CreatePostDeploymentData.createData();
            System.assert([Select id , Forecast_Duration__c from Assumption__c].size() > 0);
        } */

    @isTest
    static void testInstallScript() {
    CreatePostDeploymentData postinstall = new CreatePostDeploymentData();
        Test.testInstall(postinstall, null);
        Test.testInstall(postinstall, new Version(1,0), true);

        List<P_L_Category__c> a = [Select id, name from P_L_Category__c where name ='REVENUE'];
        System.assertEquals(a.size(), 1, 'P&L Category not found');
    }
    
}