force-app/main/default/objects/Assumption__c/Assumption__c.object-meta.xml
<CustomObject>
    <label>Assumption</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assumptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assumption__c/fields/Average_License_Price__c.field-meta.xml
<CustomField>
    <fullName>Average_License_Price__c</fullName>
    <label>Average License Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Contract_Period__c.field-meta.xml
<CustomField>
    <fullName>Contract_Period__c</fullName>
    <label>Contract Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Discounted_Receipts__c.field-meta.xml
<CustomField>
    <fullName>Discounted_Receipts__c</fullName>
    <label>Discounted Receipts %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Forecast_Duration__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Duration__c</fullName>
    <description>In Months</description>
    <label>Forecast Duration</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Forecasting_Quota__c.field-meta.xml
<CustomField>
    <fullName>Forecasting_Quota__c</fullName>
    <label>Forecasting Quota %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Hours_Per_day__c.field-meta.xml
<CustomField>
    <fullName>Hours_Per_day__c</fullName>
    <label>Hours Per Day</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Assumption__c/fields/Recurring_Revenue_Billing_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Revenue_Billing_Cycle__c</fullName>
    <label>Recurring Revenue Billing Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Semi Annually</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Annually</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cash_Forecast__c/Cash_Forecast__c.object-meta.xml
<CustomObject>
    <label>Cash Forecast</label>
    <nameField>
        <label>Cash Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cash Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Forecast__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <label>Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Cash_Statement_Setting__c/Cash_Statement_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cash Statement Setting</label>
</CustomObject>

force-app/main/default/objects/Cash_Statement_Setting__c/fields/Day_for_week_split__c.field-meta.xml
<CustomField>
    <fullName>Day_for_week_split__c</fullName>
    <label>Day for week split</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cash_Statement_Setting__c/fields/Greater_than_Min_Amt_Color__c.field-meta.xml
<CustomField>
    <fullName>Greater_than_Min_Amt_Color__c</fullName>
    <label>Greater than Min Amt Color</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cash_Statement_Setting__c/fields/Less_than_Min_Amount_Color__c.field-meta.xml
<CustomField>
    <fullName>Less_than_Min_Amount_Color__c</fullName>
    <label>Less than Min Amount Color</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cash_Statement_Setting__c/fields/Less_than_Min_Balance_Color__c.field-meta.xml
<CustomField>
    <fullName>Less_than_Min_Balance_Color__c</fullName>
    <label>Less than Min Balance Color</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cash_Statement_Setting__c/fields/Minimum_Surplus_Amount__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Surplus_Amount__c</fullName>
    <label>Minimum Surplus Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GL_Code__c/fields/PL_Category__c.field-meta.xml
<CustomField>
    <fullName>PL_Category__c</fullName>
    <description>PL_Category__c</description>
    <label>P&amp;L Category</label>
    <referenceTo>P_L_Category__c</referenceTo>
    <relationshipLabel>GL Accounts</relationshipLabel>
    <relationshipName>PL_Category</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/P_L_Category__c/P_L_Category__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Category</label>
    <nameField>
        <label>P&amp;L Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Category__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/P_L_Category__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/P_L_Formula__c/P_L_Formula__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Formula</label>
    <nameField>
        <label>P&amp;L Formulas Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Formulas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Formula__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>+</fullName>
            </value>
            <value>
                <fullName>_</fullName>
            </value>
            <value>
                <fullName>*</fullName>
            </value>
            <value>
                <fullName>/</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/P_L_Formula__c/fields/P_L_Category_A__c.field-meta.xml
<CustomField>
    <fullName>P_L_Category_A__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P&amp;L Category A</label>
    <referenceTo>P_L_Category__c</referenceTo>
    <relationshipLabel>P&amp;L Formulas</relationshipLabel>
    <relationshipName>P_L_Formulas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P_L_Formula__c/fields/P_L_Category_B__c.field-meta.xml
<CustomField>
    <fullName>P_L_Category_B__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P&amp;L Category B</label>
    <referenceTo>P_L_Category__c</referenceTo>
    <relationshipLabel>P&amp;L Formulas (P&amp;L Category B)</relationshipLabel>
    <relationshipName>P_L_Formulas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/P_L_Formula__c/fields/P_L_Formula_A__c.field-meta.xml
<CustomField>
    <fullName>P_L_Formula_A__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>P&amp;L Formula A</label>
    <referenceTo>P_L_Formula__c</referenceTo>
    <relationshipLabel>P&amp;L Formulas</relationshipLabel>
    <relationshipName>P_L_Formulas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlaceCPM_AdminSetting__c/PlaceCPM_AdminSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>PlaceCPM_AdminSetting</label>
</CustomObject>

force-app/main/default/objects/PlaceCPM_AdminSetting__c/fields/EnableDebugLog__c.field-meta.xml
<CustomField>
    <fullName>EnableDebugLog__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EnableDebugLog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PlaceCPM_AdminSetting__c/fields/PLandCashBatchFrequency__c.field-meta.xml
<CustomField>
    <fullName>PLandCashBatchFrequency__c</fullName>
    <label>PLandCashBatchFrequency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Profit_Loss__c/Profit_Loss__c.object-meta.xml
<CustomObject>
    <label>P&amp;L</label>
    <nameField>
        <label>Profit &amp; Loss Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;Ls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Profit_Loss__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <label>Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CreatePostDeploymentData.cls
global with sharing class CreatePostDeploymentData implements InstallHandler {
    static List<Assumption__c> assumptions = new List<Assumption__c>();
    
    global void onInstall(InstallContext context) {
      String orgId = UserInfo.getOrganizationId();
        if(context.previousVersion() == null) {
        createAssumption();
        //List<Assumption__c> assumptions = [Select id , Forecast_Duration__c from Assumption__c];
        List<Profit_Loss__c> plsList = new List<Profit_Loss__c>();
        List<Cash_Forecast__c> cashList = new List<Cash_Forecast__c>();
        Boolean isPLPeriodStartDate = false, isPLPeriodEndDate = false, isPLName = false;
        Boolean isCFPeriodStartDate = false, isCFPeriodEndDate = false, isCFName = false;
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.PROFIT_LOSS_OBJECT,'Period_Start_Date__c',Constant.ACTION_TYPE_INSERT)){
            isPLPeriodStartDate = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.PROFIT_LOSS_OBJECT,'Period_End_Date__c',Constant.ACTION_TYPE_INSERT)){
            isPLPeriodEndDate = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.PROFIT_LOSS_OBJECT,'Name',Constant.ACTION_TYPE_INSERT)){
            isPLName = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CASH_FORECAST_OBJECT,'Period_Start_Date__c',Constant.ACTION_TYPE_INSERT)){
            isCFPeriodStartDate = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CASH_FORECAST_OBJECT,'Period_End_Date__c',Constant.ACTION_TYPE_INSERT)){
            isCFPeriodEndDate = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CASH_FORECAST_OBJECT,'Name',Constant.ACTION_TYPE_INSERT)){
            isCFName = true;
        }
        For(Integer i = 0 ; i < assumptions[0].Forecast_Duration__c ; i++){
            Profit_Loss__c pl = new Profit_Loss__c();
            Date startDate = System.today().toStartOfMonth().addMonths(i);
            if(isPLPeriodStartDate){
                pl.Period_Start_Date__c = startDate;
            }
            Integer daysInMonth = Date.daysInMonth(startDate.year() , startDate.month());
            if(isPLPeriodEndDate){
                pl.Period_End_Date__c = startDate.addDays(daysInMonth - 1);
            }
            if(isPLName){
                pl.Name = getMonthName(startDate);
            }
            plsList.add(pl);


            Cash_Forecast__c cash = new Cash_Forecast__c();
            if(isCFPeriodStartDate){
                cash.Period_Start_Date__c = startDate;
            }
            if(isCFPeriodEndDate){
                cash.Period_End_Date__c = startDate.addDays(daysInMonth - 1);
            }
            if(isCFName){
                cash.Name = getMonthName(startDate);
            }
            cashList.add(cash);
        }

        PlaceCPM_Utility.insertRecords(plsList, CONSTANT.PROFIT_LOSS_OBJECT, false);
        PlaceCPM_Utility.insertRecords(cashList, CONSTANT.CASH_FORECAST_OBJECT, false);
        createPLCategory();
        setCustomSettings(orgId);
    }
    }
    private void setCustomSettings(String orgId){
        
        Cash_Statement_Setting__c cashSetting = new Cash_Statement_Setting__c();
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CASH_STATEMENT_CUSTOM_SETTING,'Day_for_week_split__c',Constant.ACTION_TYPE_INSERT)){
            cashSetting.Day_for_week_split__c = 'Fri';
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CASH_STATEMENT_CUSTOM_SETTING,'Greater_than_Min_Amt_Color__c',Constant.ACTION_TYPE_INSERT)){
            cashSetting.Greater_than_Min_Amt_Color__c = 'White';
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CASH_STATEMENT_CUSTOM_SETTING,'Less_than_Min_Amount_Color__c',Constant.ACTION_TYPE_INSERT)){
            cashSetting.Less_than_Min_Amount_Color__c = 'White';
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CASH_STATEMENT_CUSTOM_SETTING,'Less_than_Min_Balance_Color__c',Constant.ACTION_TYPE_INSERT)){
            cashSetting.Less_than_Min_Balance_Color__c = 'White';
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CASH_STATEMENT_CUSTOM_SETTING,'Minimum_Surplus_Amount__c',Constant.ACTION_TYPE_INSERT)){
            cashSetting.Minimum_Surplus_Amount__c = 5000.00;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.CASH_STATEMENT_CUSTOM_SETTING,'setupOwnerid',Constant.ACTION_TYPE_INSERT)){
            cashSetting.setupOwnerid = orgId;
        }

        PlaceCPM_Utility.insertRecords(new List<Cash_Statement_Setting__c>{cashSetting}, CONSTANT.CASH_STATEMENT_CUSTOM_SETTING, false);
        
        PlaceCPM_AdminSetting__c adminSetting = new PlaceCPM_AdminSetting__c();

        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.ADMIN_CUSTOM_SETTING,'EnableDebugLog__c',Constant.ACTION_TYPE_INSERT)){
            adminSetting.EnableDebugLog__c = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.ADMIN_CUSTOM_SETTING,'PLandCashBatchFrequency__c',Constant.ACTION_TYPE_INSERT)){
            adminSetting.PLandCashBatchFrequency__c = 50;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.ADMIN_CUSTOM_SETTING,'setupOwnerid',Constant.ACTION_TYPE_INSERT)){
            adminSetting.setupOwnerid = orgId;
        }
         PlaceCPM_Utility.insertRecords(new List<PlaceCPM_AdminSetting__c>{adminSetting}, CONSTANT.ADMIN_CUSTOM_SETTING, false);
    }


    private static String getMonthName(Date dateToGetName){
        Integer year = dateToGetName.year();
        Integer month = dateToGetName.month();
        String monthAndYear;
         switch on month {
                when 1 {
                    monthAndYear =  'January';
                }   
                when 2 {
                    monthAndYear =  'February';
                }
                when 3 {
                    monthAndYear =  'March';
                }
                when 4 {
                    monthAndYear =  'April';
                }
                when 5 {
                    monthAndYear =  'May';
                }
                when 6 {
                    monthAndYear =  'June';
                }
                when 7 {
                    monthAndYear =  'July';
                }
                when 8 {
                    monthAndYear =  'August';
                }
                when 9 {
                    monthAndYear =  'September';
                }
                when 10 {
                    monthAndYear =  'October';
                }
                when 11 {
                    monthAndYear =  'November';
                }
                when 12 {
                    monthAndYear =  'December';
                }
            }
        monthAndYear += ' ';
        monthAndYear += year;
        return monthAndYear;
    }


    private static void createAssumption(){
        List<Assumption__c> assumptionsNew = [Select id from Assumption__c limit 1];
        if(assumptionsNew.size() == 0){
            Assumption__c assumption = new Assumption__c();
            if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.ASSUMPTION_OBJECT,'Forecasting_Quota__c',Constant.ACTION_TYPE_INSERT)){
                assumption.Forecasting_Quota__c = 80;
            }
            if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.ASSUMPTION_OBJECT,'Average_License_Price__c',Constant.ACTION_TYPE_INSERT)){
                assumption.Average_License_Price__c = 105;
            }
            if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.ASSUMPTION_OBJECT,'Forecast_Duration__c',Constant.ACTION_TYPE_INSERT)){
                assumption.Forecast_Duration__c = 24;
            }
            if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.ASSUMPTION_OBJECT,'Contract_Period__c',Constant.ACTION_TYPE_INSERT)){
                assumption.Contract_Period__c = 12;
            }
            if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.ASSUMPTION_OBJECT,'Recurring_Revenue_Billing_Cycle__c',Constant.ACTION_TYPE_INSERT)){
                assumption.Recurring_Revenue_Billing_Cycle__c = '1';
            }
            if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.ASSUMPTION_OBJECT,'Discounted_Receipts__c',Constant.ACTION_TYPE_INSERT)){
                assumption.Discounted_Receipts__c = 10;
            }
            if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.ASSUMPTION_OBJECT,'Hours_Per_day__c',Constant.ACTION_TYPE_INSERT)){
                assumption.Hours_Per_day__c = 8;
            }
            assumptions.add(assumption);
            PlaceCPM_Utility.insertRecords(assumptions, CONSTANT.ASSUMPTION_OBJECT, false);
        }
    }


    private static void createPLCategory(){
        List<P_L_Category__c> plCategoryList = new List<P_L_Category__c>();
        P_L_Category__c plCategory;
        List<GL_Code__c> glCodeList = new List<GL_Code__c>();
        
        Map<String , String> catAndTypeMap = new Map<String , String>();
        catAndTypeMap.put('REVENUE' , 'Revenue' + ':' + 1);
        catAndTypeMap.put('COGS' , 'Expense'+ ':' + 2);
        catAndTypeMap.put('OPS AND SALES WAGES' , 'Expense'+ ':' + 3);
        catAndTypeMap.put('GENERAL AND ADMIN' , 'Expense'+ ':' + 4);
        catAndTypeMap.put('OTHER INCOME AND EXPENSES' , 'Expense'+ ':' + 5);
        
        Map<String ,  List<String>> catAndAccounts = new Map<String ,  List<String>>();
        List<String> accountAndCat;
        accountAndCat = new List<String>();
        accountAndCat.add('Channel Revenue'+ ':' + 430+ ':' + 1);
        accountAndCat.add('Intercompany Income'+ ':' + 440+ ':' + 2);
        accountAndCat.add('Other Revenue'+ ':' + 450+ ':' + 3);
        accountAndCat.add('Recurring'+ ':' + 400+ ':' + 4);
        accountAndCat.add('Time & Materials'+ ':' + 410 + ':' + 5);
        catAndAccounts.put('REVENUE' , accountAndCat);
        
        accountAndCat = new List<String>();
        accountAndCat.add('Recurring Cost of Goods Sold'+ ':' + 500  + ':' + 1);
        accountAndCat.add('Transfer Pricing Cost'+ ':' + 510 + ':' + 2);
        accountAndCat.add('Hosting'+ ':' + 520 + ':' + 3);
        accountAndCat.add('Third Party Partner Fees'+ ':' + 530 + ':' + 5);
        accountAndCat.add('Client Reimbursable Expenses'+ ':' + 540 + ':' + 6);
        accountAndCat.add('Foreign Exchange (Withholding Tax)'+ ':' + 550 + ':' + 7);
        catAndAccounts.put('COGS' , accountAndCat);
        
        accountAndCat = new List<String>();
        accountAndCat.add('Ops Wages & Salaries' + ':' + 667 + ':' + 1);
        accountAndCat.add('Sales Wages & Salaries' + ':' + 668 + ':' + 2);
        accountAndCat.add('Sales Incentives' + ':' + 669 + ':' + 3);
        catAndAccounts.put('OPS AND SALES WAGES' , accountAndCat);
        
        accountAndCat = new List<String>();
        accountAndCat.add('Advertising' + ':' + 600 + ':' + 1);
        accountAndCat.add('Bad Debt Expense' + ':' + 690 + ':' + 2);
        accountAndCat.add('Blueprint Expenses' + ':' + 691 + ':' + 3);
        accountAndCat.add('Charitable Contributions' + ':' + 644 + ':' + 4);
        accountAndCat.add('Client Gifts' + ':' + 648+ ':' + 5) ;
        accountAndCat.add('Dues and Subscriptions' + ':' + 676+ ':' + 6);
        accountAndCat.add('General Expenses' + ':' + 628+ ':' + 7);
        accountAndCat.add('Income Tax Expense' + ':' + 710+ ':' + 8);
        accountAndCat.add('Insurance' + ':' + 632+ ':' + 9);
        accountAndCat.add('Internal I Costs' + ':' + 608+ ':' + 10);
        accountAndCat.add('Office Expenses' + ':' + 640+ ':' + 11);
        accountAndCat.add('Payroll Tax Expense' + ':' + 672+ ':' + 12);
        accountAndCat.add('Professional Development & Incentives' + ':' + 664+ ':' + 13);
        accountAndCat.add('Professional Fees' + ':' + 612+ ':' + 14);
        accountAndCat.add('Recruiting' + ':' + 656+ ':' + 15);
        accountAndCat.add('Rent' + ':' + 660+ ':' + 16);
        accountAndCat.add('Research & Development' + ':' + 665+ ':' + 17);
        accountAndCat.add('Telephone & Internet' + ':' + 680+ ':' + 18);
        accountAndCat.add('Travel' + ':' + 684+ ':' + 19);
        catAndAccounts.put('GENERAL AND ADMIN' , accountAndCat);
        accountAndCat = new List<String>();
        accountAndCat.add('Depreciation Expense' + ':' + 700 + ':' + 1);
        accountAndCat.add('Bank Service Charges' + ':' + 604 + ':' + 2);
        accountAndCat.add('Interest Expense' + ':' + 800 + ':' + 3);
        catAndAccounts.put('OTHER INCOME AND EXPENSES' , accountAndCat);
        String[] temp;
        Boolean isPLCatName = false, isPLCatType = false, isPLCatSequence = false;
		if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.PL_CATEGORY_OBJECT,'Name',Constant.ACTION_TYPE_INSERT)){
            isPLCatName = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.PL_CATEGORY_OBJECT,'Type__c',Constant.ACTION_TYPE_INSERT)){
            isPLCatType = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.PL_CATEGORY_OBJECT,'Sequence__c',Constant.ACTION_TYPE_INSERT)){
            isPLCatSequence = true;
        }
        For(String key : catAndTypeMap.keySet()){
           plCategory = new P_L_Category__c();
           if(isPLCatName){
                plCategory.Name = key;
           }
           temp = catAndTypeMap.get(key).split(':');
           if(isPLCatType){
                plCategory.Type__c = temp[0];
           }
           if(isPLCatSequence){
                plCategory.Sequence__c = Integer.valueOf(temp[1]);
           }
           plCategoryList.add(plCategory);
        }

        PlaceCPM_Utility.insertRecords(plCategoryList, CONSTANT.PL_CATEGORY_OBJECT, false);
        
        
       // List<P_L_Category__c> plclist = [Select id , Name from P_L_Category__c];
        Map<String , Id> plcNameAndId = new Map<String , Id>();
        For(P_L_Category__c plc : plCategoryList){
            plcNameAndId.put(plc.Name , plc.Id);
        }
        Boolean isNameCreatable = false, isPLCategoryA = false, isPLCategoryB = false, isOperatorCreatable = false;
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.PL_CATEGORY_OBJECT,'Name',Constant.ACTION_TYPE_INSERT)){
            isNameCreatable = true;
        }
            isPLCategoryA = true;
            isPLCategoryB = true;
            isOperatorCreatable = true;

        List<P_L_Formula__c> formulaList = new List<P_L_Formula__c>();
        P_L_Formula__c plf = new P_L_Formula__c();
        if(isNameCreatable){
            plf.Name = 'GROSS PROFIT';
        }
        if(isPLCategoryA){
            plf.P_L_Category_A__c = plcNameAndId.get('REVENUE');
        }
        if(isPLCategoryB){
            plf.P_L_Category_B__c = plcNameAndId.get('COGS');
        }
        if(isOperatorCreatable){
            plf.Operator__c = '_';
        }
        formulaList.add(plf);


        P_L_Formula__c plf1 = new P_L_Formula__c();
        if(isNameCreatable){
            plf1.Name = 'GROSS CONTRIBUTION';
        }
        if(isPLCategoryA){
            plf1.P_L_Formula_A__c = plf.Id;
        }
        if(isPLCategoryB){
            plf1.P_L_Category_B__c = plcNameAndId.get('OPS AND SALES WAGES');
        }
        if(isOperatorCreatable){
            plf1.Operator__c = '_';
        }
        formulaList.add(plf1);


        P_L_Formula__c plf2 = new P_L_Formula__c();
        if(isNameCreatable){
            plf2.Name = 'EBITDA';
        }
        if(isPLCategoryA){
            plf2.P_L_Formula_A__c = plf1.Id;
        }
        if(isPLCategoryB){
            plf2.P_L_Category_B__c = plcNameAndId.get('GENERAL AND ADMIN');
        }
        if(isOperatorCreatable){
            plf2.Operator__c = '_';
        }
        formulaList.add(plf2);


        P_L_Formula__c plf3 = new P_L_Formula__c();
        if(isNameCreatable){
        plf3.Name = 'NET INCOME';
        }
        if(isPLCategoryA){
        plf3.P_L_Formula_A__c = plf2.Id;
        }
        if(isPLCategoryB){
            plf3.P_L_Category_B__c = plcNameAndId.get('OTHER INCOME AND EXPENSES');
        }
        if(isOperatorCreatable){
            plf3.Operator__c = '_';
        }
        formulaList.add(plf3);


        PlaceCPM_Utility.insertRecords(formulaList, CONSTANT.PL_FORMULA_OBJECT, false);
        
        GL_Code__c glc;
        String[] glcTempArr;
        Boolean isGLName = false, isGLCode = false, isGLSequence = false, isGLPLCategory = false;
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.GL_CODE_OBJECT,'Name',Constant.ACTION_TYPE_INSERT)){
            isGLName = false;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.GL_CODE_OBJECT,'GL_Code__c',Constant.ACTION_TYPE_INSERT)){
            isGLCode = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.GL_CODE_OBJECT,'Sequence__c',Constant.ACTION_TYPE_INSERT)){
            isGLSequence = true;
        }
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.GL_CODE_OBJECT,'PL_Category__c',Constant.ACTION_TYPE_INSERT)){
            isGLPLCategory = true;
        }
        For(P_L_Category__c plc : plCategoryList){
            For(String glcString : catAndAccounts.get(plc.Name)){
                glc = new GL_Code__c();
                glcTempArr = glcString.split(':');
                if(isGLName){
                    glc.Name = glcTempArr[0];
                }
                if(isGLCode){
                    glc.GL_Code__c = Integer.valueOf(glcTempArr[1]);
                }
                if(isGLSequence){
                    glc.Sequence__c = Integer.valueOf(glcTempArr[2]);
                }
                if(isGLPLCategory){
                    glc.PL_Category__c = plc.Id;
                }
                glCodeList.add(glc);
            }
        }
        PlaceCPM_Utility.insertRecords(glCodeList, CONSTANT.GL_CODE_OBJECT, false);
    }
}


/*public with sharing class CreatePostDeploymentData {
    public static void createData() {
        createAssumption();
        List<Assumption__c> assumptions = [Select id , Forecast_Duration__c from Assumption__c];
        List<Profit_Loss__c> plsList = new List<Profit_Loss__c>();
        List<Cash_Forecast__c> cashList = new List<Cash_Forecast__c>();
        For(Integer i = 0 ; i < assumptions[0].Forecast_Duration__c ; i++){
            Profit_Loss__c pl = new Profit_Loss__c();
            Date startDate = System.today().toStartOfMonth().addMonths(i);
            pl.Period_Start_Date__c = startDate;
            Integer daysInMonth = Date.daysInMonth(startDate.year() , startDate.month());
            pl.Period_End_Date__c = startDate.addDays(daysInMonth - 1);
            pl.Name = getMonthName(startDate);
            plsList.add(pl);
            Cash_Forecast__c cash = new Cash_Forecast__c();
            cash.Period_Start_Date__c = startDate;
            cash.Period_End_Date__c = startDate.addDays(daysInMonth - 1);
            cash.Name = getMonthName(startDate);
            cashList.add(cash);
        }
        insert plsList;
        insert cashList;
        createPLCategory();
        //Test
    }
     public static void createPLCategory(){
        List<P_L_Category__c> plCategoryList = new List<P_L_Category__c>();
        P_L_Category__c plCategory;
        List<GL_Code__c> glCodeList = new List<GL_Code__c>();
        
        Map<String , String> catAndTypeMap = new Map<String , String>();
        catAndTypeMap.put('REVENUE' , 'Revenue' + ':' + 1);
        catAndTypeMap.put('COGS' , 'Expense'+ ':' + 2);
        catAndTypeMap.put('OPS AND SALES WAGES' , 'Expense'+ ':' + 3);
        catAndTypeMap.put('GENERAL AND ADMIN' , 'Expense'+ ':' + 4);
        catAndTypeMap.put('OTHER INCOME AND EXPENSES' , 'Expense'+ ':' + 5);
        
        Map<String ,  List<String>> catAndAccounts = new Map<String ,  List<String>>();
        List<String> accountAndCat;
        accountAndCat = new List<String>();
        accountAndCat.add('Channel Revenue'+ ':' + 430+ ':' + 1);
        accountAndCat.add('Intercompany Income'+ ':' + 440+ ':' + 2);
        accountAndCat.add('Other Revenue'+ ':' + 450+ ':' + 3);
        accountAndCat.add('Recurring'+ ':' + 400+ ':' + 4);
        accountAndCat.add('Time & Materials'+ ':' + 410 + ':' + 5);
        catAndAccounts.put('REVENUE' , accountAndCat);
        
        accountAndCat = new List<String>();
        accountAndCat.add('Recurring Cost of Goods Sold'+ ':' + 500  + ':' + 1);
        accountAndCat.add('Transfer Pricing Cost'+ ':' + 510 + ':' + 2);
        accountAndCat.add('Hosting'+ ':' + 520 + ':' + 3);
        accountAndCat.add('Third Party Partner Fees'+ ':' + 530 + ':' + 5);
        accountAndCat.add('Client Reimbursable Expenses'+ ':' + 540 + ':' + 6);
        accountAndCat.add('Foreign Exchange (Withholding Tax)'+ ':' + 550 + ':' + 7);
        catAndAccounts.put('COGS' , accountAndCat);
        
        accountAndCat = new List<String>();
        accountAndCat.add('Ops Wages & Salaries' + ':' + 667 + ':' + 1);
        accountAndCat.add('Sales Wages & Salaries' + ':' + 668 + ':' + 2);
        accountAndCat.add('Sales Incentives' + ':' + 669 + ':' + 3);
        catAndAccounts.put('OPS AND SALES WAGES' , accountAndCat);
        
        accountAndCat = new List<String>();
        accountAndCat.add('Advertising' + ':' + 600 + ':' + 1);
        accountAndCat.add('Bad Debt Expense' + ':' + 690 + ':' + 2);
        accountAndCat.add('Blueprint Expenses' + ':' + 691 + ':' + 3);
        accountAndCat.add('Charitable Contributions' + ':' + 644 + ':' + 4);
        accountAndCat.add('Client Gifts' + ':' + 648+ ':' + 5) ;
        accountAndCat.add('Dues and Subscriptions' + ':' + 676+ ':' + 6);
        accountAndCat.add('General Expenses' + ':' + 628+ ':' + 7);
        accountAndCat.add('Income Tax Expense' + ':' + 710+ ':' + 8);
        accountAndCat.add('Insurance' + ':' + 632+ ':' + 9);
        accountAndCat.add('Internal IT Costs' + ':' + 608+ ':' + 10);
        accountAndCat.add('Office Expenses' + ':' + 640+ ':' + 11);
        accountAndCat.add('Payroll Tax Expense' + ':' + 672+ ':' + 12);
        accountAndCat.add('Professional Development & Incentives' + ':' + 664+ ':' + 13);
        accountAndCat.add('Professional Fees' + ':' + 612+ ':' + 14);
        accountAndCat.add('Recruiting' + ':' + 656+ ':' + 15);
        accountAndCat.add('Rent' + ':' + 660+ ':' + 16);
        accountAndCat.add('Research & Development' + ':' + 665+ ':' + 17);
        accountAndCat.add('Telephone & Internet' + ':' + 680+ ':' + 18);
        accountAndCat.add('Travel' + ':' + 684+ ':' + 19);
        catAndAccounts.put('GENERAL AND ADMIN' , accountAndCat);
        accountAndCat = new List<String>();
        accountAndCat.add('Depreciation Expense' + ':' + 700 + ':' + 1);
        accountAndCat.add('Bank Service Charges' + ':' + 604 + ':' + 2);
        accountAndCat.add('Interest Expense' + ':' + 800 + ':' + 3);
        catAndAccounts.put('OTHER INCOME AND EXPENSES' , accountAndCat);
        String[] temp;
        For(String key : catAndTypeMap.keySet()){
           plCategory = new P_L_Category__c();
           plCategory.Name = key;
           temp = catAndTypeMap.get(key).split(':');
           plCategory.Type__c = temp[0];
           plCategory.Sequence__c = Integer.valueOf(temp[1]);
           plCategoryList.add(plCategory);
        }
        insert plCategoryList;
        
        List<P_L_Category__c> plclist = [Select id , Name from P_L_Category__c];
        Map<String , Id> plcNameAndId = new Map<String , Id>();
        For(P_L_Category__c plc : plclist){
            plcNameAndId.put(plc.Name , plc.Id);
        }
        
        List<P_L_Formula__c> formulaList = new List<P_L_Formula__c>();
        P_L_Formula__c plf = new P_L_Formula__c();
        plf.Name = 'GROSS PROFIT';
        plf.P_L_Category_A__c = plcNameAndId.get('REVENUE');
        plf.P_L_Category_B__c = plcNameAndId.get('COGS');
        formulaList.add(plf);
        P_L_Formula__c plf1 = new P_L_Formula__c();
        plf1.Name = 'GROSS CONTRIBUTION';
        plf1.P_L_Formula_A__c = plf.Id;
        plf1.P_L_Category_B__c = plcNameAndId.get('OPS AND SALES WAGES');
        formulaList.add(plf1);
        P_L_Formula__c plf2 = new P_L_Formula__c();
        plf2.Name = 'EBITDA';
        plf2.P_L_Formula_A__c = plf1.Id;
        plf2.P_L_Category_B__c = plcNameAndId.get('GENERAL AND ADMIN');
        formulaList.add(plf2);
        P_L_Formula__c plf3 = new P_L_Formula__c();
        plf3.Name = 'NET INCOME';
        plf3.P_L_Formula_A__c = plf2.Id;
        plf3.P_L_Category_B__c = plcNameAndId.get('OTHER INCOME AND EXPENSES');
        formulaList.add(plf3);
        insert formulaList;
        
        GL_Code__c glc;
        String[] glcTempArr;
        For(P_L_Category__c plc : plclist){
            For(String glcString : catAndAccounts.get(plc.Name)){
                glc = new GL_Code__c();
                glcTempArr = glcString.split(':');
                glc.Name = glcTempArr[0];
                glc.GL_Code__c = Integer.valueOf(glcTempArr[1]);
                glc.Sequence__c = Integer.valueOf(glcTempArr[2]);
                glc.PL_Category__c = plc.Id;
                glCodeList.add(glc);
            }
        }
        insert glCodeList;
    }
    
    public static void createAssumption(){
        List<Assumption__c> assumptions = [Select id from Assumption__c];
        if(assumptions.size() == 0){
            Assumption__c assumption = new Assumption__c();
            assumption.Forecasting_Quota__c = 80;
            assumption.Average_License_Price__c = 105;
            assumption.Forecast_Duration__c = 24;
            assumption.Contract_Period__c = 12;
            insert assumption;  
        }
    }
    
    public static String getMonthName(Date dateToGetName){
        Integer year = dateToGetName.year();
        Integer month = dateToGetName.month();
        String monthAndYear;
         switch on month {
                when 1 {
                    monthAndYear =  'January';
                }   
                when 2 {
                    monthAndYear =  'February';
                }
                when 3 {
                    monthAndYear =  'March';
                }
                when 4 {
                    monthAndYear =  'April';
                }
                when 5 {
                    monthAndYear =  'May';
                }
                when 6 {
                    monthAndYear =  'June';
                }
                when 7 {
                    monthAndYear =  'July';
                }
                when 8 {
                    monthAndYear =  'August';
                }
                when 9 {
                    monthAndYear =  'September';
                }
                when 10 {
                    monthAndYear =  'October';
                }
                when 11 {
                    monthAndYear =  'November';
                }
                when 12 {
                    monthAndYear =  'December';
                }
            }
        monthAndYear += ' ';
        monthAndYear += year;
        return monthAndYear;
    }
}*/