force-app/main/default/objects/Assumption__c/Assumption__c.object-meta.xml
<CustomObject>
    <label>Assumption</label>
    <nameField>
        <displayFormat>FA-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assumptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assumption__c/fields/Forecast_Duration__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Duration__c</fullName>
    <description>In Months</description>
    <label>Forecast Duration</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bonus_Plan__c/Bonus_Plan__c.object-meta.xml
<CustomObject>
    <label>Bonus Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bonus Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bonus_Plan__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Semi-Annually</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Annually</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bonus_Plan__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <label>Percentage</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Cash_Forecast__c/Cash_Forecast__c.object-meta.xml
<CustomObject>
    <label>Cash Forecast</label>
    <nameField>
        <label>Cash Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cash Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Forecast__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <label>Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Compensation__c/Compensation__c.object-meta.xml
<CustomObject>
    <label>Compensation</label>
    <nameField>
        <displayFormat>Comp - {00000}</displayFormat>
        <label>Compensation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compensation__c/fields/Bonus_Plan__c.field-meta.xml
<CustomField>
    <fullName>Bonus_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bonus Plan</label>
    <referenceTo>Bonus_Plan__c</referenceTo>
    <relationshipLabel>Compensations</relationshipLabel>
    <relationshipName>Bonus_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compensation__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Compensations</relationshipLabel>
    <relationshipName>Compensations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compensation__c/recordTypes/Sales_Employee_Compensation.recordType-meta.xml
<RecordType>
    <fullName>Sales_Employee_Compensation</fullName>
    <active>true</active>
    <label>Sales Employee Compensation</label>
</RecordType>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organization</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Role</label>
    <referenceTo>Role__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Category__c/P_L_Category__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Category</label>
    <nameField>
        <label>P&amp;L Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Category__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Profit_Loss__c/Profit_Loss__c.object-meta.xml
<CustomObject>
    <label>P&amp;L</label>
    <nameField>
        <label>Profit &amp; Loss Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;Ls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Profit_Loss__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <label>Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Wages__c/Wages__c.object-meta.xml
<CustomObject>
    <label>Wage</label>
    <nameField>
        <displayFormat>Wage-{00000000}</displayFormat>
        <label>Wages Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wages__c/fields/Compensation__c.field-meta.xml
<CustomField>
    <fullName>Compensation__c</fullName>
    <label>Compensation</label>
    <referenceTo>Compensation__c</referenceTo>
    <relationshipLabel>Wages</relationshipLabel>
    <relationshipName>Wages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CompensationTriggerHandlerTest.cls
@isTest 
private class CompensationTriggerHandlerTest {
    static Assumption__c assumptionRec;
    static Employee__c employeeRec;
    static List<Bonus_Plan__c> bonusPlanList = new List<Bonus_Plan__c>();
    static List<Compensation__c> compensationList = new List<Compensation__c>();
    public static  void createPLandCash(){
        assumptionRec = TestUtility.createAssumption(10,True);
        List<Profit_Loss__c> plsList = new List<Profit_Loss__c>();
        List<Cash_Forecast__c> cashList = new List<Cash_Forecast__c>();
        For(Integer i = 0 ; i < 12 ; i++){
            Profit_Loss__c pl = new Profit_Loss__c();
            Date startDate = System.today().toStartOfMonth().addMonths(i);
            pl.Period_Start_Date__c = startDate;
            Integer daysInMonth = Date.daysInMonth(startDate.year() , startDate.month());
            pl.Period_End_Date__c = startDate.addDays(daysInMonth - 1);
            pl.Name = PlaceCPM_Utility.getMonthName(startDate);
            plsList.add(pl);
            Cash_Forecast__c cash = new Cash_Forecast__c();
            cash.Period_Start_Date__c = startDate;
            cash.Period_End_Date__c = startDate.addDays(daysInMonth - 1);
            cash.Name = PlaceCPM_Utility.getMonthName(startDate);
            cashList.add(cash);
        }
        insert plsList;
        insert cashList;
    }
    
    static testMethod void createtestData(){
        createPLandCash();
        P_L_Category__c plCategory = TestUtility.createPlCategory('General and Admin','Expense',false);
        plCategory.Sequence__c = 1;
        insert plCategory;
        GL_Code__c glaccount = TestUtility.createGLCode('Advertising',600,plCategory.id,True);
        Organisation__c organisation = TestUtility.createOrganisation('Place Technology', true); 
        Department__c department = TestUtility.createDepartment('SFDC', organisation.Id, glaccount.Id, true);  
        Role__c role = TestUtility.createRole('Tester', department.Id ,true);
        employeeRec = TestUtility.createEmployee('TestEmployee',role.Id,System.today(),'Austin','Salaried Employee',CONSTANT.EMPLOYEE_SALES_RT,true);
        Integer month = 1;
        do{
            bonusPlanList.add(new Bonus_Plan__c (Name='i',Percentage__c =10, Payment_Frequency__c = String.valueOf(month)));
            if(month == 1){
                month += 2;
            } else {
               month = month * 2; 
            }
        } while(month < 12) ; 
        insert bonusPlanList;
    }
    static testMethod void CompensationTestMethod2(){
        list<Compensation__c> listcom = new list<Compensation__c>();
        createtestData();
        Test.startTest();
        Id comSalesRecordTypeId = PlaceCPM_Utility.getRecordTypeIdbyDeveloperName('Compensation__c','Sales_Employee_Compensation');
        Compensation__c comRecord = TestUtility.createCompensation(System.today(),System.today().addDays(60),employeeRec.id, 10,'Monthly', bonusPlanList[0].id,False);
        comRecord.recordTypeId = comSalesRecordTypeId;
        insert comRecord;
        Compensation__c comRecord1 = TestUtility.createCompensation(System.today().addDays(40), System.today().addDays(45),employeeRec.id, 10,'Weekly', bonusPlanList[1].id,False);
        comRecord1.recordTypeId = comSalesRecordTypeId;
        insert comRecord1;
        Compensation__c comRecord2 = TestUtility.createCompensation(System.today().addDays(50), System.today().addDays(60),employeeRec.id, 10,'Bi-Weekly', bonusPlanList[1].id,False);
        comRecord2.recordTypeId = comSalesRecordTypeId;
        insert comRecord2;
        Compensation__c com = TestUtility.createCompensation(System.today().addDays(70), System.today().addDays(75),employeeRec.id, 10,'Semi-Monthly', bonusPlanList[2].id,False);
        com.recordTypeId = comSalesRecordTypeId;
        insert com;
        delete com;
        listcom = [Select Id from Compensation__c where Id =: com.id];
        System.assert(listcom.size() == 0,'Compensation has not been deleted');
        Test.stopTest();
    }  
    static testMethod void CompensationTestMethod3(){
       createtestData();
       Id comSalesRecordTypeId = PlaceCPM_Utility.getRecordTypeIdbyDeveloperName('Compensation__c','Sales_Employee_Compensation');
       Test.startTest();
       Compensation__c com = TestUtility.createCompensation(System.today().addDays(80), System.today().addDays(90),employeeRec.id, 10,'Monthly', bonusPlanList[2].id,False);
       com.recordTypeId = comSalesRecordTypeId;
       insert com;
       com.End_Date__c = System.today().addDays(95);
       //update com;
       System.assert(com.End_Date__c == System.today().addDays(95), 'End Date is not populated correctly');
       Test.stopTest();
    }     
   static testMethod void CompensationTestMethod4(){
       createtestData();
       Id comSalesRecordTypeId = PlaceCPM_Utility.getRecordTypeIdbyDeveloperName('Compensation__c','Sales_Employee_Compensation');
       Test.startTest();
       Compensation__c com = TestUtility.createCompensation(System.today().addDays(100), System.today().addDays(110),employeeRec.id, 10,'Semi-Monthly', bonusPlanList[2].id,False);
       com.recordTypeId = comSalesRecordTypeId;
       insert com;
       System.assertEquals(True, [Select Id From Wages__c where Compensation__c =: com.Id].size() > 0);
       Test.stopTest();
   } 
   static testMethod void CompensationTestMethod5(){
       createtestData();
       Id comSalesRecordTypeId = PlaceCPM_Utility.getRecordTypeIdbyDeveloperName('Compensation__c','Sales_Employee_Compensation');
       Test.startTest();
       Compensation__c com = TestUtility.createCompensation(System.today().addDays(35), System.today().addDays(40),employeeRec.id, 10,'Semi-Monthly', bonusPlanList[2].id,False);
       com.recordTypeId = comSalesRecordTypeId;
       insert com;
       System.assertEquals(comSalesRecordTypeId, [Select Id,recordTypeId from Compensation__c].recordTypeId);
       Test.stopTest();
   } 
   static testMethod void CompensationTestMethod6(){
       createtestData();
       Id comSalesRecordTypeId = PlaceCPM_Utility.getRecordTypeIdbyDeveloperName('Compensation__c','Sales_Employee_Compensation');
       Test.startTest();
       Compensation__c com = TestUtility.createCompensation(System.today().addDays(35), System.today().addDays(40),employeeRec.id, 10,'Weekly', bonusPlanList[2].id,False);
       com.recordTypeId = comSalesRecordTypeId;
       insert com;
       System.assertEquals(True, [Select Id From Wages__c where Compensation__c =: com.Id].size() > 0);
       Test.stopTest();
   }  
   static testMethod void CompensationTestMethod7(){
       createtestData();
       Id comSalesRecordTypeId = PlaceCPM_Utility.getRecordTypeIdbyDeveloperName('Compensation__c','Sales_Employee_Compensation');
       Test.startTest();
       Compensation__c com = TestUtility.createCompensation(System.today().addDays(35), System.today().addDays(40),employeeRec.id, 10,'Weekly', bonusPlanList[2].id,False);
       com.recordTypeId = comSalesRecordTypeId;
       insert com;
       assumptionRec.Forecast_Duration__c = null;
       com.End_Date__c = null;
       update com;
       System.assertEquals(True, [Select Start_Date__c from Compensation__c limit 1].Start_Date__c <= [Select Cash_Date__c  from Wages__c limit 1].Cash_Date__c );
       Test.stopTest();
   }  
    
}