force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organization</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Departments</relationshipLabel>
    <relationshipName>Departments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor(Expense Account)</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Role</label>
    <referenceTo>Role__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Expense_Allocation__c/Employee_Expense_Allocation__c.object-meta.xml
<CustomObject>
    <label>Employee Expense Allocation</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Expense Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Expense_Allocation__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Expense Allocations</relationshipLabel>
    <relationshipName>Employee_Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Expense_Allocation__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Employee Expense Allocations</relationshipLabel>
    <relationshipName>Employee_Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/Expense_Account__c.object-meta.xml
<CustomObject>
    <label>Expense Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Account__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>GL_Code__c.PL_Category__r.Type__c</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>GL_Code__c</referenceTo>
    <relationshipLabel>Expense Accounts</relationshipLabel>
    <relationshipName>Expense_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/fields/P_L_Category__c.field-meta.xml
<CustomField>
    <fullName>P_L_Category__c</fullName>
    <formula>GL_Code__r.PL_Category__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>P&amp;L Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Account__c/recordTypes/General.recordType-meta.xml
<RecordType>
    <fullName>General</fullName>
    <active>true</active>
    <label>General</label>
</RecordType>

force-app/main/default/objects/Expense_Allocation__c/Expense_Allocation__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Expense Allocation</label>
    <nameField>
        <displayFormat>EAN-{00000}</displayFormat>
        <label>Expense Allocation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Allocation__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Expense Allocations</relationshipLabel>
    <relationshipName>Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Allocation__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense Allocations</relationshipLabel>
    <relationshipName>Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Allocation__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Expense Allocations</relationshipLabel>
    <relationshipName>Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Allocation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role</label>
    <referenceTo>Role__c</referenceTo>
    <relationshipLabel>Expense Allocations</relationshipLabel>
    <relationshipName>Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/Expense_Detail__c.object-meta.xml
<CustomObject>
    <description>Object to Store Time frame and Amount Information related to Expense Account.</description>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>ED - {0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Detail__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense Details</relationshipLabel>
    <relationshipName>Expense_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/recordTypes/Recurring.recordType-meta.xml
<RecordType>
    <fullName>Recurring</fullName>
    <active>true</active>
    <description>This record type represents the Recurring record type.</description>
    <label>Recurring</label>
</RecordType>

force-app/main/default/objects/GL_Code__c/GL_Code__c.object-meta.xml
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GL_Code__c/fields/GL_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Code__c</fullName>
    <label>GL Code</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/P_L_Category__c/P_L_Category__c.object-meta.xml
<CustomObject>
    <label>P&amp;L Category</label>
    <nameField>
        <label>P&amp;L Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>P&amp;L Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <description>PCPM-235</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Role__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Roles</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ExpenseAllocationTriggerHandlerTest.cls
/*
 * Class : ExpenseAllocationTriggerHandlerTest
 * Date  : 12 July 2019
 * Description - Test Class for ExpenseAllocationTriggerHandler | PCPM-235 | Namita | 12 July
 * 
 * Change 1 : Namita  | PCPM-322 | 23 July 19
 * Change 2 : Namita  | PCPM-329 | 25 July 19
 */

@isTest 
public class ExpenseAllocationTriggerHandlerTest {
    public static GL_Code__c glaccount;
    public static Organisation__c organisation;
    public static Department__c department;
    public static Role__c role;
    public static Expense_Account__c expenseAccount;
    public static Employee__c emp; //PCPM-322
    
    @isTest
    public static void testExpenseAllocationTriggerHandler1(){
        createData();
        Test.startTest();
            Expense_Allocation__c  expenseAlloc1 = TestUtility.createExpenseAllocation(expenseAccount.Id, false);
            expenseAlloc1.Organisation__c = organisation.Id; 
            expenseAlloc1.Department__c = department.Id; 
            expenseAlloc1.Role__c = role.Id; 
            insert expenseAlloc1;
        
            //PCPM-322
            List<Employee_Expense_Allocation__c> empExpenseAllocList = [SELECT Id, Employee__c FROM Employee_Expense_Allocation__c WHERE Employee__c=: emp.id];
            System.assertEquals(1, empExpenseAllocList.size());
        Test.stopTest();
    }
    
    @isTest
    public static void testExpenseAllocationTriggerHandler2(){
        createData();
        Test.startTest();
            Expense_Allocation__c  expenseAlloc1 = TestUtility.createExpenseAllocation(expenseAccount.Id, false);
            expenseAlloc1.Organisation__c = organisation.Id; 
            expenseAlloc1.Department__c = department.Id; 
            insert expenseAlloc1;
            List<Employee_Expense_Allocation__c> empExpenseAllocList = [SELECT Id, Employee__c FROM Employee_Expense_Allocation__c WHERE Employee__c=: emp.id];
            System.assertEquals(1, empExpenseAllocList.size());
       Test.stopTest(); 
    }
    
    @isTest
    public static void testExpenseAllocationTriggerHandler3(){
        createData();
        Test.startTest();
            Expense_Allocation__c  expenseAlloc1 = TestUtility.createExpenseAllocation(expenseAccount.Id, false);
            expenseAlloc1.Department__c = department.Id; 
            expenseAlloc1.Role__c = role.Id; 
            insert expenseAlloc1;
            List<Employee_Expense_Allocation__c> empExpenseAllocList = [SELECT Id, Employee__c FROM Employee_Expense_Allocation__c WHERE Employee__c=: emp.id];
            System.assertEquals(1, empExpenseAllocList.size());
       Test.stopTest(); 
    }
    
    @isTest
    public static void testExpenseAllocationTriggerHandler5(){
        createData();
        Test.startTest();
            Expense_Allocation__c  expenseAlloc1 = TestUtility.createExpenseAllocation(expenseAccount.Id, false);
            expenseAlloc1.Department__c = department.Id;
            insert expenseAlloc1;
            List<Employee_Expense_Allocation__c> empExpenseAllocList = [SELECT Id, Employee__c FROM Employee_Expense_Allocation__c WHERE Employee__c=: emp.id];
            System.assertEquals(1, empExpenseAllocList.size());
       Test.stopTest(); 
    }
    
    @isTest
    public static void testExpenseAllocationTriggerHandler6(){
        createData();
        Test.startTest();
            Expense_Allocation__c  expenseAlloc1 = TestUtility.createExpenseAllocation(expenseAccount.Id, false);
            expenseAlloc1.Organisation__c = organisation.Id; 
            insert expenseAlloc1;
            List<Employee_Expense_Allocation__c> empExpenseAllocList = [SELECT Id, Employee__c FROM Employee_Expense_Allocation__c WHERE Employee__c=: emp.id];
            System.assertEquals(1, empExpenseAllocList.size());
       Test.stopTest(); 
    }
    
    public static void createData(){
        Account acc = TestUtility.createAccount('TestAccount',true);
        
        P_L_Category__c plCategory = TestUtility.createPlCategory('General and Admin','Expense',true);
        glaccount = TestUtility.createGLCode('Recurring',600,plCategory.id,true);
        
        organisation = TestUtility.createOrganisation('Place Technology', true);
        department = TestUtility.createDepartment('SFDC', organisation.Id, glaccount.Id, true);  
        role = TestUtility.createRole('Tester', department.Id ,true);
        
        expenseAccount = TestUtility.createExpenseAccount(acc.Id, glaccount.Id, '1', true);
        //PCPM-322
        Expense_Detail__c expenseDetail = TestUtility.createExpenseDetail(expenseAccount.Id,System.today().addDays(-2) , System.today().addDays(60), System.today().addDays(10),2000 ,'30', true);
        emp = TestUtility.createEmployee('TestEmployee',role.Id, System.today(),'Austin','Salaried Employee',CONSTANT.EMPLOYEE_SALES_RT,true);
        System.assert(plCategory != null);            
    }
}