force-app/main/default/objects/Cash_Forecast__c/Cash_Forecast__c.object-meta.xml
<CustomObject>
    <label>Cash Forecast</label>
    <nameField>
        <label>Cash Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cash Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Account__c/Expense_Account__c.object-meta.xml
<CustomObject>
    <label>Expense Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expense Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Account__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Quarterly</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Semi Annually</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Annually</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Cash_Allocation__c/Expense_Cash_Allocation__c.object-meta.xml
<CustomObject>
    <label>Expense Cash Allocation</label>
    <nameField>
        <displayFormat>ECA-{000000}-{000}</displayFormat>
        <label>Expense Cash Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Cash Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/Cash_Date__c.field-meta.xml
<CustomField>
    <fullName>Cash_Date__c</fullName>
    <label>Cash Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/Cash_Forecast__c.field-meta.xml
<CustomField>
    <fullName>Cash_Forecast__c</fullName>
    <label>Cash Forecast</label>
    <referenceTo>Cash_Forecast__c</referenceTo>
    <relationshipLabel>Expense Cash Allocations</relationshipLabel>
    <relationshipName>Expense_Cash_Alllocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense Cash Allocations</relationshipLabel>
    <relationshipName>Expense_Cash_Alllocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Cash_Allocation__c/fields/Expense_Detail__c.field-meta.xml
<CustomField>
    <fullName>Expense_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Detail</label>
    <referenceTo>Expense_Detail__c</referenceTo>
    <relationshipLabel>Expense Cash Allocations</relationshipLabel>
    <relationshipName>Expense_Cash_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/Expense_Detail__c.object-meta.xml
<CustomObject>
    <description>Object to Store Time frame and Amount Information related to Expense Account.</description>
    <label>Expense Detail</label>
    <nameField>
        <displayFormat>ED - {0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Detail__c/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Auto Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense Details</relationshipLabel>
    <relationshipName>Expense_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/fields/Monthly_Expense_Amount__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Expense_Amount__c</fullName>
    <formula>IF(Is_Annual_Amount__c,  Expense_Amount__c / 12, Expense_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Expense Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <formula>Text(Expense_Account__r.Payment_Frequency__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Detail__c/fields/Payment_Term_After_Days__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_After_Days__c</fullName>
    <label>Payment Term (After # Days)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Term_After_Days</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/Expense_PL_Allocation__c.object-meta.xml
<CustomObject>
    <label>Expense GL Allocation</label>
    <nameField>
        <displayFormat>EPLA-{000000}-{000}</displayFormat>
        <label>Expense P&amp;L Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense GL Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Expense_Account__c.field-meta.xml
<CustomField>
    <fullName>Expense_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Account</label>
    <referenceTo>Expense_Account__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Wage_Expense_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/Expense_Detail__c.field-meta.xml
<CustomField>
    <fullName>Expense_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense Detail</label>
    <referenceTo>Expense_Detail__c</referenceTo>
    <relationshipLabel>Expense GL Allocations</relationshipLabel>
    <relationshipName>Expense_P_L_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_PL_Allocation__c/fields/PlMonthStartDate__c.field-meta.xml
<CustomField>
    <fullName>PlMonthStartDate__c</fullName>
    <formula>P_L__r.Period_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PlMonthStartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Payment_Term_After_Days.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
        <default>true</default>
        <label>On Delivery</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>Net 15</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Net 30</label>
    </customValue>
    <customValue>
        <fullName>45</fullName>
        <label>Net 45</label>
    </customValue>
    <customValue>
        <fullName>60</fullName>
        <label>Net 60</label>
    </customValue>
    <customValue>
        <fullName>75</fullName>
        <label>Net 75</label>
    </customValue>
    <customValue>
        <fullName>90</fullName>
        <label>Net 90</label>
    </customValue>
    <masterLabel>Payment Term (After # Days)</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ExpensePLAllocationTriggerHandler.cls
/*
Description : This class will be as Handler for ExpensePLAllocationTrigger
Date Created : 17th June 2019
*/
public with sharing class ExpensePLAllocationTriggerHandler implements CommonTriggerHandler{
    public static boolean dontRunTrigger = false;
    public void BeforeInsert(List<SObject> newItems){
    
    }
    
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems){
        
    }
    
    public void BeforeDelete(Map<Id, SObject> oldItems){
        CreatePLStatements.createCategoryStatements(null , oldItems);
    }
    
    public void AfterInsert(Map<Id, SObject> newItems){
        CreatePLStatements.createCategoryStatements(newItems.values() , null);
    }
    
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems){
        CreatePLStatements.createCategoryStatements(newItems.values() , oldItems);
        updateCashAllocationData((Map<Id, Expense_PL_Allocation__c>)newItems , (Map<Id, Expense_PL_Allocation__c>)oldItems);
    }
    
    public void AfterDelete(Map<Id, SObject> oldItems){
    }
    
    public void AfterUndelete(Map<Id, SObject> oldItems){
    }
    
    public Boolean IsDisabled(){
        return false;
    }

    //  Method to update cash allocation related to pl allocation record.
    //  @param newItems new map containing Expense_PL_Allocation__c, oldItems items before changes containing Expense_PL_Allocation__c
    //  @return void
    public void updateCashAllocationData(Map<Id, Expense_PL_Allocation__c> newItems, Map<Id, Expense_PL_Allocation__c> oldItems) {
        Set<String> expenseAccountId = new Set<String>();
        Set<String> expenseDetailId = new Set<String>();
        Map<String, Expense_Cash_Allocation__c> expenseCashMap = new Map<String, Expense_Cash_Allocation__c>();
        for(Expense_PL_Allocation__c expensePL : newItems.values()) {
            expenseAccountId.add(expensePL.Expense_Account__c);
            expenseDetailId.add(expensePL.Expense_Detail__c);
        }
        
        if(PlaceCPM_Utility.checkAccessiblityOfFields(Constant.EXPENSE_DETAIL_OBJECT,'Id, Expense_Account__c,Monthly_Expense_Amount__c, Payment_Frequency__c,Invoice_Date__c,Auto_Renew__c,Payment_Term_After_Days__c,Start_Date__c',Constant.ACTION_TYPE_ACCESS) && 
           PlaceCPM_Utility.checkAccessiblityOfFields(Constant.EXPENSE_CASG_ALLOCATION_OBJECT,'Id, Cash_Forecast__c,Cash_Date__c, Forecast_Amount__c',Constant.ACTION_TYPE_ACCESS) && 
           PlaceCPM_Utility.checkAccessiblityOfFields(Constant.EXPENSE_PL_ALLOCATION_OBJECT,'Id, PlMonthStartDate__c,Forecast_Amount__c, Actual_Amount__c',Constant.ACTION_TYPE_ACCESS)){
        for(Expense_Detail__c ed : [Select Id, Expense_Account__c, 
                                    Monthly_Expense_Amount__c, Payment_Frequency__c,
                                    Invoice_Date__c,Auto_Renew__c,
                                    Payment_Term_After_Days__c,Start_Date__c ,
                                    (Select Id, Cash_Forecast__c, 
                                     Cash_Date__c, Forecast_Amount__c,
                                     Cash_Forecast__r.Name
                                     From Expense_Cash_Allocations__r),
                                    (Select Id, PlMonthStartDate__c,Forecast_Amount__c, Actual_Amount__c
                                     From Expense_P_L_Allocations__r Order by PlMonthStartDate__c)
                                    From Expense_Detail__c
                                    Where Id in : expenseDetailId]) {
                                        //expenseCashMap = new Map<String, Expense_Cash_Allocation__c>(); //562
                                        Integer expenseMonths = ed.Expense_P_L_Allocations__r.size();
                                        for(Expense_Cash_Allocation__c cash : ed.Expense_Cash_Allocations__r){
                                            expenseCashMap.put(String.valueOf(cash.Cash_Date__c), cash);
                                        }
                                        if(ed.Start_Date__c != null && expenseMonths > 0 && ed.Payment_Frequency__c != null){
                                            if(ed.Payment_Term_After_Days__c != null){
                                                Integer totalCashAllocationRecords = Integer.valueOf(expenseMonths)/Integer.valueOf(ed.Payment_Frequency__c);
                                                Integer lastyearMonths = math.mod(Integer.valueOf(expenseMonths), Integer.valueOf(ed.Payment_Frequency__c));
                                                if(lastyearMonths!=0){
                                                    totalCashAllocationRecords=totalCashAllocationRecords+1;
                                                }
                                                Date cashDate = ed.Invoice_Date__c .addDays(ed.Payment_Term_After_Days__c !=null ? Integer.valueOf(ed.Payment_Term_After_Days__c): 0);
                                                Date futureDate;
												Date plDate = ed.Expense_P_L_Allocations__r[0].PlMonthStartDate__c;
                                                Date endDate = plDate.addMonths(Integer.valueOf(ed.Payment_Frequency__c));
                                                for(Integer i=0; i<totalCashAllocationRecords; i++){
                                                    futureDate = cashDate.addMonths((i*Integer.valueOf(ed.Payment_Frequency__c)));
                                                    if(expenseCashMap.containsKey(String.valueOf(futureDate))) {
                                                        Expense_Cash_Allocation__c eca = expenseCashMap.get(String.valueOf(futureDate));
                                                        eca.Forecast_Amount__c = 0;
                                                        eca.Actual_Amount__c = 0;
                                                        for(Expense_PL_Allocation__c expensePL : ed.Expense_P_L_Allocations__r) { 
                                                            if(expensePL.PlMonthStartDate__c >= plDate && expensePL.PlMonthStartDate__c < endDate) {
                                                                eca.Forecast_Amount__c += expensePL.Forecast_Amount__c;
                                                                if(expensePL.Actual_Amount__c != null){
                                                                    eca.Actual_Amount__c += expensePL.Actual_Amount__c;
                                                                }
                                                                plDate = expensePL.PlMonthStartDate__c.addDays(1);
                                                            }
                                                        }
                                                        endDate = plDate.addMonths(Integer.valueOf(ed.Payment_Frequency__c));
                                                        expenseCashMap.put(String.valueOf(eca.Cash_Date__c), eca);
                                                    }
                                                }
                                            }
                                        }
                                    }
    	}
        PlaceCPM_Utility.updateRecords(expenseCashMap.values(), CONSTANT.EXPENSE_CASG_ALLOCATION_OBJECT, false); //520                                    
    }
}